// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Limits over a real source database, on each engine: a composed server over
 * a fresh database whose tables carry `table.capacity` as stored overrides,
 * public endpoints made the way an app's install makes them, and the write
 * service handed a target the way a staff route hands one.
 *
 * `poolMax` (or `ADMINIUM_TEST_SOURCE_POOL_MAX`, which the test task passes
 * through) sets the source pool's size: a guard that checks out a second
 * connection inside its transaction stalls a pool of one.
 *
 * Postgres and MySQL gate on TEST_POSTGRES_URL / TEST_MYSQL_URL (`''` counts
 * as absent).
 */
import { randomBytes } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import BetterSqlite3 from 'better-sqlite3';
import { sql, type Kysely } from 'kysely';
import { AdapterRegistry, type AdapterProvider } from '@adminium/engine/adapter';
import { connectionTenantConfig, createSqliteMetaDb, firstRun, overridesRepo, settingsRepo, snapshotsRepo, type MetaDb } from '@adminium/meta';

import { composeServer, type ComposedServer } from '../src/compose.js';
import { applyOverrides } from '../src/connections/effective-schema.js';
import { dsnCryptoFromSecret } from '../src/connections/crypto.js';
import { runIntrospection } from '../src/connections/introspect.js';
import { ConnectionManager, type SourceDatabase } from '../src/connections/manager.js';
import { registerAdapters } from '../src/connections/register-adapters.js';
import { SnapshotView } from '../src/crud/identifiers.js';
import type { Row } from '../src/crud/mask.js';
import { normalizeWriteValue } from '../src/crud/write-values.js';
import { createWriteService, insertRows, uncheckedForUndo, type RecordWriteService, type WriteOrigin, type WriteTarget } from '../src/crud/write-service.js';
import { createApplyService } from '../src/llm/apply-service.js';
import { createRunService } from '../src/llm/run-service.js';
import type { MetaStoreHandle } from '../src/meta/store.js';
import { createEndpointService } from '../src/public-api/endpoint-service.js';
import type { PublicEndpointDefinition } from '../src/public-api/endpoint.js';
import { generatePublishableKey, sealPublishableKey } from '../src/public-api/keys.js';
import { createPublicViews } from '../src/public-api/runtime.js';
import { makeEnv, TEST_SECRET } from './helpers.js';

export type Dialect = 'sqlite' | 'postgres' | 'mysql';
const POSTGRES_URL = process.env.TEST_POSTGRES_URL || undefined;
const MYSQL_URL = process.env.TEST_MYSQL_URL || undefined;
export const ORIGIN = 'https://venue.example.com';

export const LEGS: [Dialect, boolean][] = [
  ['sqlite', true],
  ['postgres', POSTGRES_URL !== undefined],
  ['mysql', MYSQL_URL !== undefined],
];

/** The source pool's size the harness asks for, when a test does not say. */
export const TEST_POOL_MAX = process.env.ADMINIUM_TEST_SOURCE_POOL_MAX ? Number(process.env.ADMINIUM_TEST_SOURCE_POOL_MAX) : undefined;

/** Each engine's spelling of the column types the tests use. */
export function types(dialect: Dialect) {
  return {
    key: dialect === 'postgres' ? 'integer generated by default as identity primary key' : dialect === 'mysql' ? 'int auto_increment primary key' : 'integer primary key',
    at: dialect === 'postgres' ? 'timestamptz' : dialect === 'mysql' ? 'datetime' : 'timestamp',
    date: 'date',
    bool: dialect === 'postgres' ? 'boolean' : dialect === 'mysql' ? 'boolean' : 'boolean',
    text: (n: number) => `varchar(${String(n)})`,
    /** A foreign key, as a table constraint every engine keeps (MySQL ignores one written on the column). */
    fk: (column: string, table: string) => `foreign key (${column}) references ${table}(id)`,
  };
}

export interface WorldSpec {
  zone: string;
  ddl: (dialect: Dialect) => string[];
  /** Overrides, given the tables' snapshot ids. */
  overrides: (id: (table: string) => string) => { op: string; table: string; column?: string; value: unknown }[];
  /** Public endpoints by ref (without `path` and `source`'s id resolved: `source` is a table name). */
  endpoints?: Record<string, Record<string, unknown>>;
  poolMax?: number | undefined;
}

export interface World {
  dialect: Dialect;
  connectionId: string;
  db: Kysely<SourceDatabase>;
  meta: MetaDb;
  app: ComposedServer['app'];
  id: (table: string) => string;
  writes: RecordWriteService;
  /** A target for a table, as a staff route builds it (the venue's zone set). */
  target: (table: string) => Promise<WriteTarget>;
  create: (table: string, values: Row, origin?: WriteOrigin) => Promise<Row>;
  update: (table: string, id: unknown, values: Row, origin?: WriteOrigin) => Promise<Row | null>;
  /** Rows put straight in, without any rule (history). */
  seed: (table: string, rows: Row[]) => Promise<void>;
  query: (text: string) => Promise<Record<string, unknown>[]>;
  /** The public API, with the key made for the endpoints. */
  get: (path: string, session?: string) => Promise<{ status: number; body: Record<string, unknown> }>;
  post: (path: string, payload: unknown) => Promise<{ status: number; body: Record<string, unknown> }>;
  patch: (path: string, payload: unknown, session?: string) => Promise<{ status: number; body: Record<string, unknown> }>;
  close: () => Promise<void>;
}

function memoryStore(meta: MetaDb): MetaStoreHandle {
  return { meta, url: 'sqlite::memory:', engine: 'sqlite', source: 'embedded', close: async () => Promise.resolve() };
}

export async function world(dialect: Dialect, spec: WorldSpec): Promise<World> {
  const dataDir = await mkdtemp(join(tmpdir(), 'capacity-'));
  const meta = createSqliteMetaDb({ database: new BetterSqlite3(':memory:') });
  await firstRun(meta);
  const registry = new AdapterRegistry<AdapterProvider>();
  await registerAdapters(registry);
  const poolMax = spec.poolMax ?? TEST_POOL_MAX;
  const manager = new ConnectionManager({
    meta,
    crypto: dsnCryptoFromSecret(TEST_SECRET),
    registry,
    metaDsn: null,
    blockLoopback: false,
    ...(poolMax === undefined ? {} : { sourcePoolMax: poolMax }),
  });

  const name = `adminium_cap_${randomBytes(4).toString('hex')}`;
  let dsn: string;
  let drop: () => Promise<void> = async () => undefined;
  if (dialect === 'sqlite') {
    const file = join(dataDir, 'venue.db');
    new BetterSqlite3(file).close();
    dsn = `sqlite:${file}`;
  } else if (dialect === 'postgres') {
    const { Client } = await import('pg');
    const admin = new Client({ connectionString: POSTGRES_URL });
    await admin.connect();
    await admin.query(`CREATE DATABASE ${name}`);
    await admin.end();
    const url = new URL(POSTGRES_URL!);
    url.pathname = `/${name}`;
    dsn = url.toString();
    drop = async () => {
      const again = new Client({ connectionString: POSTGRES_URL });
      await again.connect();
      await again.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);
      await again.end();
    };
  } else {
    const mysql = await import('mysql2/promise');
    const admin = await mysql.createConnection(MYSQL_URL!);
    await admin.query(`CREATE DATABASE \`${name}\``);
    await admin.end();
    const url = new URL(MYSQL_URL!);
    url.pathname = `/${name}`;
    dsn = url.toString();
    drop = async () => {
      const again = await mysql.createConnection(MYSQL_URL!);
      await again.query(`DROP DATABASE IF EXISTS \`${name}\``);
      await again.end();
    };
  }
  const connection = await manager.connections.create({ name: 'Venue', engine: dialect, introspectDsn: dsn, dataDsn: dsn });
  await meta.db.updateTable('adminium_connections').set({ timezone: spec.zone }).where('id', '=', connection.id).execute();
  const { db } = await manager.data(connection.id);
  for (const statement of spec.ddl(dialect)) await sql.raw(statement).execute(db);
  await runIntrospection({ manager, meta, connectionId: connection.id });

  const snapshot = (await snapshotsRepo(meta).latest(connection.id))!;
  const tables = (snapshot.schema as { tables: { id: string; name: string }[] }).tables;
  const id = (table: string) => {
    const found = tables.find((t) => t.name === table);
    if (found === undefined) throw new Error(`no table ${table}`);
    return found.id;
  };
  const overrides = overridesRepo(meta);
  for (const o of spec.overrides(id)) {
    await overrides.create({
      connectionId: connection.id,
      op: o.op as never,
      tableName: id(o.table),
      ...(o.column === undefined ? {} : { columnName: o.column }),
      value: o.value as never,
    });
  }

  const runService = createRunService({ meta });
  const composed: ComposedServer = await composeServer({
    env: makeEnv({ ADMINIUM_PUBLIC_API_ORIGINS: ORIGIN, HOST: '127.0.0.1', ADMINIUM_SECRET: TEST_SECRET }),
    metaStore: memoryStore(meta),
    manager,
    runService,
    applyService: createApplyService({ meta, runService }),
    allowed: null,
    logger: false,
    telemetry: false,
  });
  await composed.app.ready();
  await settingsRepo(meta).set('publicApi.enabled', true);

  let token = '';
  const refs = Object.keys(spec.endpoints ?? {});
  if (refs.length > 0) {
    const views = createPublicViews(meta);
    const service = createEndpointService({
      meta,
      viewFor: views.viewFor,
      tenantConfigOf: async (cid) => (await connectionTenantConfig(meta, cid)) ?? undefined,
    });
    const access: { ref: string; methods: string[] }[] = [];
    for (const [ref, definition] of Object.entries(spec.endpoints!)) {
      const def: Record<string, unknown> = {
        filters: [],
        pagination: { default_limit: 50, max_limit: 200, order: 'id.asc' },
        rate_limit: { requests: 6000, window: '1m' },
        response: { shape: 'object', envelope: 'data' },
        auth: { role: 'anon' },
        select: ['id'],
        ...definition,
        source: id(String(definition['source'])),
        path: `/${ref}`,
      };
      await service.saveEndpoint({ connectionId: connection.id, ref, definition: def as unknown as PublicEndpointDefinition, origin: 'custom', managedBy: 'venue' });
      access.push({ ref, methods: def['methods'] as string[] });
    }
    const generated = generatePublishableKey('browser');
    await service.createKey({
      connectionId: connection.id,
      name: 'Venue · guests',
      access: access as never,
      secret: { prefix: generated.prefix, tokenHash: generated.tokenHash, tokenEncrypted: sealPublishableKey(dsnCryptoFromSecret(TEST_SECRET), generated.token) },
      origins: [],
      kind: 'browser',
      managedBy: 'venue',
    });
    token = generated.token;
  }

  const writes = createWriteService();
  const target = async (table: string): Promise<WriteTarget> => {
    const latest = (await snapshotsRepo(meta).latest(connection.id))!;
    const active = await overridesRepo(meta).listForConnection(connection.id, { status: 'active' });
    const view = new SnapshotView(connection.id, applyOverrides(latest.schema as never, active), new Map());
    const data = await manager.data(connection.id);
    return { connectionId: connection.id, view, table: view.table(id(table)), db: data.db, dialect: data.dialect, timezone: spec.zone };
  };
  // Values as a route hands them on: each read for its column (a time's zone kept).
  const prepared = (t: WriteTarget, values: Row) =>
    Object.fromEntries(Object.entries(values).map(([k, v]) => [k, t.table.columns.has(k) ? normalizeWriteValue(t.table.columns.get(k)!, v) : v]));
  const context = (origin: WriteOrigin) => ({ origin, hops: 0, actor: null, request: null });
  const headers = (session?: string) => ({
    authorization: `Bearer ${token}`,
    origin: ORIGIN,
    ...(session === undefined ? {} : { 'x-adminium-public-session': session }),
  });
  const answer = (res: { statusCode: number; body: string }) => ({ status: res.statusCode, body: (res.body === '' ? {} : JSON.parse(res.body)) as Record<string, unknown> });
  const app = composed.app;
  return {
    dialect,
    connectionId: connection.id,
    db,
    meta,
    app,
    id,
    writes,
    target,
    create: async (table, values, origin = 'dashboard') => {
      const t = await target(table);
      return writes.create({ target: t, values: prepared(t, values), context: context(origin), announce: async () => {} });
    },
    update: async (table, key, values, origin = 'dashboard') => {
      const t = await target(table);
      return (await writes.update({ target: t, pk: { id: key }, values: prepared(t, values), context: context(origin), announce: async () => {} })).after;
    },
    seed: async (table, rows) => {
      const t = await target(table);
      await insertRows(db, t.dialect, t.table, uncheckedForUndo(rows.map((row) => prepared(t, row))));
      // Keys given by hand: the next one made is after them.
      if (dialect === 'postgres' && rows.some((row) => row['id'] !== undefined)) {
        await sql.raw(`select setval(pg_get_serial_sequence('${t.table.id}', 'id'), (select max(id) from ${t.table.id}))`).execute(db);
      }
    },
    query: async (text) => (await sql.raw(text).execute(db)).rows as Record<string, unknown>[],
    get: async (path, session) => answer(await app.inject({ method: 'GET', url: `/api/v1/public/${path}`, headers: headers(session) })),
    post: async (path, payload) => answer(await app.inject({ method: 'POST', url: `/api/v1/public/${path}`, headers: headers(), payload: payload as never })),
    patch: async (path, payload, session) => answer(await app.inject({ method: 'PATCH', url: `/api/v1/public/${path}`, headers: headers(session), payload: payload as never })),
    close: async () => {
      await composed.app.close();
      await manager.disposeAll().catch(() => undefined);
      await drop();
      await meta.db.destroy();
      await rm(dataDir, { recursive: true, force: true });
    },
  };
}

/** The error code of a refused write (thrown by the write service). */
export async function refusal(run: Promise<unknown>): Promise<{ code: string; details: Record<string, unknown> } | 'ok'> {
  try {
    await run;
    return 'ok';
  } catch (error) {
    const e = error as { code?: string; details?: Record<string, unknown> };
    if (e.code === undefined) throw error;
    return { code: e.code, details: e.details ?? {} };
  }
}

/** Make a world and fill it; a world whose filling fails is closed before the error is thrown. */
export async function filled(dialect: Dialect, spec: WorldSpec, fill: (w: World) => Promise<void>): Promise<World> {
  const w = await world(dialect, spec);
  try {
    await fill(w);
    return w;
  } catch (error) {
    await w.close();
    throw error;
  }
}
