// SPDX-License-Identifier: AGPL-3.0-only
/**
 * A guest's booking, end to end over the public API, on every engine: which
 * times of a day have room, the booking itself, the slot filling up, a claimed
 * guest changing theirs, and cancelling too late.
 *
 * Nothing is faked below the HTTP route: a real source database carries the
 * booking limit as an override, the key is made from endpoints the way an
 * app's install makes them, and every answer comes from the composed server.
 */
import { randomBytes } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import BetterSqlite3 from 'better-sqlite3';
import { sql } from 'kysely';
import { afterEach, describe, expect, it } from 'vitest';
import { AdapterRegistry, type AdapterProvider } from '@adminium/engine/adapter';
import {
  connectionTenantConfig,
  createSqliteMetaDb,
  firstRun,
  overridesRepo,
  settingsRepo,
  snapshotsRepo,
  type MetaDb,
} from '@adminium/meta';

import { composeServer, type ComposedServer } from '../src/compose.js';
import { dsnCryptoFromSecret } from '../src/connections/crypto.js';
import { runIntrospection } from '../src/connections/introspect.js';
import { ConnectionManager } from '../src/connections/manager.js';
import { registerAdapters } from '../src/connections/register-adapters.js';
import { venueClock, wallTimeToInstant } from '../src/crud/venue-time.js';
import { createApplyService } from '../src/llm/apply-service.js';
import { createRunService } from '../src/llm/run-service.js';
import type { MetaStoreHandle } from '../src/meta/store.js';
import { createEndpointService } from '../src/public-api/endpoint-service.js';
import type { PublicEndpointDefinition } from '../src/public-api/endpoint.js';
import { generatePublishableKey, sealPublishableKey } from '../src/public-api/keys.js';
import { createPublicViews } from '../src/public-api/runtime.js';
import { decryptSecret, encryptSecret } from '../src/config/secrets.js';
import { emailSecretKey } from '../src/email/config.js';
import { emailEnvelopeKey } from '../src/email/send.js';
import { makeEnv, TEST_SECRET } from './helpers.js';

type Dialect = 'sqlite' | 'postgres' | 'mysql';
const POSTGRES_URL = process.env.TEST_POSTGRES_URL;
const MYSQL_URL = process.env.TEST_MYSQL_URL || undefined;
const ORIGIN = 'https://cafe.example.com';
const ZONE = 'Europe/London';

let close: (() => Promise<void>) | null = null;
afterEach(async () => {
  await close?.();
  close = null;
});

function memoryStore(meta: MetaDb): MetaStoreHandle {
  return { meta, url: 'sqlite::memory:', engine: 'sqlite', source: 'embedded', close: async () => Promise.resolve() };
}

/** The two tables, as each engine spells them. */
function ddl(dialect: Dialect): string[] {
  const key = dialect === 'postgres' ? 'integer generated by default as identity primary key' : dialect === 'mysql' ? 'int auto_increment primary key' : 'integer primary key';
  const at = dialect === 'postgres' ? 'timestamptz' : dialect === 'mysql' ? 'datetime' : 'timestamp';
  return [
    `create table booking_rules (id ${key}, covers integer not null, cancel_hours integer not null)`,
    `create table reservations (id ${key}, code varchar(7) unique, starts_at ${at} not null, party integer not null, status varchar(16) not null default 'booked', name varchar(40), mobile varchar(20), email varchar(80))`,
    `create table venue (id ${key}, venue_name varchar(40) not null, address varchar(80), phone varchar(20))`,
    'insert into booking_rules (covers, cancel_hours) values (6, 2)',
    "insert into venue (venue_name, address, phone) values ('Martin''s', '128 Alder Lane', '(415) 555-0148')",
  ];
}

async function serving(dialect: Dialect) {
  const dataDir = await mkdtemp(join(tmpdir(), 'availability-'));
  const meta = createSqliteMetaDb({ database: new BetterSqlite3(':memory:') });
  await firstRun(meta);
  const registry = new AdapterRegistry<AdapterProvider>();
  await registerAdapters(registry);
  const manager = new ConnectionManager({ meta, crypto: dsnCryptoFromSecret(TEST_SECRET), registry, metaDsn: null, blockLoopback: false });

  const name = `adminium_avail_${randomBytes(4).toString('hex')}`;
  let dsn: string;
  let drop: () => Promise<void> = async () => undefined;
  if (dialect === 'sqlite') {
    const file = join(dataDir, 'cafe.db');
    new BetterSqlite3(file).close();
    dsn = `sqlite:${file}`;
  } else if (dialect === 'postgres') {
    const { Client } = await import('pg');
    const admin = new Client({ connectionString: POSTGRES_URL });
    await admin.connect();
    await admin.query(`CREATE DATABASE ${name}`);
    await admin.end();
    const url = new URL(POSTGRES_URL as string);
    url.pathname = `/${name}`;
    dsn = url.toString();
    drop = async () => {
      const again = new Client({ connectionString: POSTGRES_URL });
      await again.connect();
      await again.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);
      await again.end();
    };
  } else {
    const mysql = await import('mysql2/promise');
    const admin = await mysql.createConnection(MYSQL_URL as string);
    await admin.query(`CREATE DATABASE \`${name}\``);
    await admin.end();
    const url = new URL(MYSQL_URL as string);
    url.pathname = `/${name}`;
    dsn = url.toString();
    drop = async () => {
      const again = await mysql.createConnection(MYSQL_URL as string);
      await again.query(`DROP DATABASE IF EXISTS \`${name}\``);
      await again.end();
    };
  }
  const connection = await manager.connections.create({ name: 'Cafe', engine: dialect, introspectDsn: dsn, dataDsn: dsn });
  await meta.db.updateTable('adminium_connections').set({ timezone: ZONE }).where('id', '=', connection.id).execute();
  const { db } = await manager.data(connection.id);
  for (const statement of ddl(dialect)) await sql.raw(statement).execute(db);
  await runIntrospection({ manager, meta, connectionId: connection.id });

  const snapshot = (await snapshotsRepo(meta).latest(connection.id))!;
  const tables = (snapshot.schema as { tables: { id: string; name: string }[] }).tables;
  const idOf = (table: string) => tables.find((t) => t.name === table)!.id;
  const rules = idOf('booking_rules');
  const venueTable = idOf('venue');
  const reservations = idOf('reservations');
  const overrides = overridesRepo(meta);
  await overrides.create({
    connectionId: connection.id,
    op: 'table.capacity',
    tableName: reservations,
    value: {
      slot: 'starts_at',
      amount: 'party',
      perSlot: { table: rules, column: 'covers' },
      countWhere: { column: 'status', values: ['booked'] },
      slotMinutes: 30,
      windowDays: 5,
      opens: '17:00',
      closes: '21:00',
      cancelHours: { table: rules, column: 'cancel_hours' },
    },
  });
  await overrides.create({ connectionId: connection.id, op: 'column.code', tableName: reservations, columnName: 'code', value: { prefix: 'MR-', length: 4 } });
  await overrides.create({ connectionId: connection.id, op: 'column.validation', tableName: reservations, columnName: 'mobile', value: { format: 'phone' } });

  const runService = createRunService({ meta });
  const composed: ComposedServer = await composeServer({
    env: makeEnv({ ADMINIUM_PUBLIC_API_ORIGINS: ORIGIN, HOST: '127.0.0.1', ADMINIUM_SECRET: TEST_SECRET }),
    metaStore: memoryStore(meta),
    manager,
    runService,
    applyService: createApplyService({ meta, runService }),
    allowed: null,
    logger: false,
    telemetry: false,
  });
  await composed.app.ready();
  await settingsRepo(meta).set('publicApi.enabled', true);
  // Mail is on: the confirmation is queued (and sealed) for delivery.
  await settingsRepo(meta).set('email.smtp', {
    host: 'localhost',
    port: 587,
    user: 'postmaster',
    passEncrypted: encryptSecret('hunter2', emailSecretKey(TEST_SECRET)),
    from: 'Adminium <no-reply@adminium.test>',
    secure: false,
  } as never);

  // The endpoints and the key, as an app's install makes them.
  const views = createPublicViews(meta);
  const service = createEndpointService({
    meta,
    viewFor: views.viewFor,
    tenantConfigOf: async (id) => (await connectionTenantConfig(meta, id)) ?? undefined,
  });
  const base = {
    source: reservations,
    filters: [],
    pagination: { default_limit: 50, max_limit: 200, order: 'id.asc' },
    rate_limit: { requests: 600, window: '1m' },
    response: { shape: 'object', envelope: 'data' },
  };
  const endpoints: Record<string, Record<string, unknown>> = {
    reservations: {
      ...base,
      methods: ['POST'],
      select: ['id', 'code', 'starts_at', 'party'],
      writable: ['starts_at', 'party', 'name', 'mobile', 'email'],
      defaults: { status: 'booked' },
      auth: { role: 'anon' },
      confirm: {
        template: 'booking-confirmation',
        to: 'email',
        code: 'code',
        when: 'starts_at',
        party: 'party',
        name: 'name',
        venue: { table: venueTable, name: 'venue_name', address: 'address', phone: 'phone' },
        link: 'manage?code={code}',
      },
    },
    reservations_claimed: {
      ...base,
      methods: ['GET', 'PATCH'],
      select: ['id', 'code', 'starts_at', 'party', 'status'],
      writable: ['starts_at', 'party', 'status'],
      auth: { role: 'authenticated' },
      identity: { strategy: 'lookup', match: ['code', 'mobile'], column: 'id' },
    },
    reservations_availability: { ...base, methods: ['GET'], select: ['id'], auth: { role: 'anon' }, kind: 'availability' },
  };
  for (const [ref, definition] of Object.entries(endpoints)) {
    await service.saveEndpoint({ connectionId: connection.id, ref, definition: { path: `/${ref}`, ...definition } as PublicEndpointDefinition, origin: 'custom', managedBy: 'pos' });
  }
  const generated = generatePublishableKey('browser');
  await service.createKey({
    connectionId: connection.id,
    name: 'Cafe · guests',
    access: [
      { ref: 'reservations', methods: ['POST'] },
      { ref: 'reservations_claimed', methods: ['GET', 'PATCH'] },
      { ref: 'reservations_availability', methods: ['GET'] },
    ],
    secret: { prefix: generated.prefix, tokenHash: generated.tokenHash, tokenEncrypted: sealPublishableKey(dsnCryptoFromSecret(TEST_SECRET), generated.token) },
    origins: [],
    kind: 'browser',
    managedBy: 'pos',
  });

  close = async () => {
    await composed.app.close();
    await manager.disposeAll().catch(() => undefined);
    await drop();
    await meta.db.destroy();
    await rm(dataDir, { recursive: true, force: true });
  };

  const headers = (session?: string) => ({
    authorization: `Bearer ${generated.token}`,
    origin: ORIGIN,
    ...(session === undefined ? {} : { 'x-adminium-public-session': session }),
  });
  const app = composed.app;
  return {
    db,
    reservations,
    availability: async (day: string, party: number, session?: string) => {
      const res = await app.inject({ method: 'GET', url: `/api/v1/public/availability/reservations_availability?date=${day}&party=${String(party)}`, headers: headers(session) });
      expect(res.statusCode, res.body).toBe(200);
      return Object.fromEntries((res.json() as { data: { time: string; state: string }[] }).data.map((s) => [s.time, s.state]));
    },
    book: (at: string, party: number, mobile = '07700900001', email?: string, language?: string) =>
      app.inject({
        method: 'POST',
        url: '/api/v1/public/records/reservations',
        headers: { ...headers(), ...(language === undefined ? {} : { 'accept-language': language }) },
        payload: { values: { starts_at: at, party, name: 'Guest', mobile, ...(email === undefined ? {} : { email }) } },
      }),
    /** The confirmation mail queued, opened as the delivery job would open it. */
    mail: async () => {
      const jobs = await meta.db.selectFrom('adminium_jobs').selectAll().where('kind', '=', 'email.send').execute();
      return jobs.map((job) => {
        const payload = (typeof job.payload === 'string' ? JSON.parse(job.payload) : job.payload) as { templateKey: string; locale: string; envelope: string };
        const envelope = JSON.parse(decryptSecret(payload.envelope, emailEnvelopeKey(TEST_SECRET))) as { to: string; subject: string; text: string };
        return { template: payload.templateKey, locale: payload.locale, ...envelope };
      });
    },
    claim: async (code: string, mobile: string) => {
      const res = await app.inject({ method: 'POST', url: '/api/v1/public/claim', headers: headers(), payload: { match: { code, mobile } } });
      expect(res.statusCode, res.body).toBe(200);
      return (res.json() as { data: { session: string } }).data.session;
    },
    /** The claim's answer code, when it refuses. */
    claimRefused: async (code: string, mobile: string) => {
      const res = await app.inject({ method: 'POST', url: '/api/v1/public/claim', headers: headers(), payload: { match: { code, mobile } } });
      return res.statusCode === 200 ? 'claimed' : codeOf(res);
    },
    change: (session: string, id: unknown, values: Record<string, unknown>) =>
      app.inject({ method: 'PATCH', url: `/api/v1/public/records/reservations_claimed/${String(id)}`, headers: headers(session), payload: { values } }),
    rows: (ref: string) => app.inject({ method: 'GET', url: `/api/v1/public/records/${ref}`, headers: headers() }),
  };
}

const codeOf = (res: { json: () => unknown }) => (res.json() as { error?: { code?: string } }).error?.code;

const legs: [Dialect, boolean][] = [
  ['sqlite', true],
  ['postgres', POSTGRES_URL !== undefined],
  ['mysql', MYSQL_URL !== undefined],
];

for (const [dialect, available] of legs) {
  describe.skipIf(!available)(`a guest booking on ${dialect}`, () => {
    it('sees free or full, fills a slot, changes theirs, and cannot cancel too late', async () => {
      const guest = await serving(dialect);
      const day = venueClock(new Date(Date.now() + 2 * 86_400_000), ZONE).day;
      const at = (time: string) => wallTimeToInstant(`${day} ${time}`, ZONE)!.toISOString();

      // The venue's day: 17:00 to 20:30, every half hour, all free for four.
      const empty = await guest.availability(day, 4);
      expect(Object.keys(empty)).toEqual(['17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30']);
      expect(new Set(Object.values(empty))).toEqual(new Set(['free']));

      // A booking of four at seven: the server gives it a code.
      const first = await guest.book(at('19:00'), 4, '07700900001');
      expect(first.statusCode, first.body).toBe(201);
      const booked = (first.json() as { data: { id: unknown; code: string; starts_at: unknown } }).data;
      expect(booked.code).toMatch(/^MR-[0-9A-HJKMNP-TV-Z]{4}$/);
      // The instant it is, on every engine — SQLite keeps the server's wall clock, which a guest elsewhere cannot read.
      expect(new Date(String(booked.starts_at)).toISOString()).toBe(at('19:00'));
      expect(String(booked.starts_at)).toMatch(/Z$|[+-]\d{2}:?\d{2}$/);
      expect(await guest.availability(day, 2)).toMatchObject({ '19:00': 'free', '19:30': 'free' });
      expect(await guest.availability(day, 3)).toMatchObject({ '19:00': 'full', '19:30': 'free' });

      // A booking with an email is confirmed in the guest's language; one without is not.
      expect(await guest.mail()).toEqual([]);
      expect((await guest.book(at('19:00'), 2, '07700900002', 'ada@example.com', 'de-DE,de;q=0.9')).statusCode).toBe(201);
      const [mail] = await guest.mail();
      expect(mail).toMatchObject({ template: 'booking-confirmation', locale: 'de_DE', to: 'ada@example.com' });
      expect(mail!.subject).toBe('Ihr Tisch bei Martin’s ist reserviert'.replace('’', "'"));
      expect(mail!.text).toMatch(/Buchungscode: MR-[0-9A-HJKMNP-TV-Z]{4}/);
      expect(mail!.text).toContain('Personen: 2');
      expect(mail!.text).toContain('19:00');
      expect(mail!.text).toContain('manage?code=MR-');
      expect(mail!.text).toContain('bis 2 Stunden');
      expect(mail!.text).toContain('128 Alder Lane');
      const full = await guest.book(at('19:00'), 1, '07700900003');
      expect(full.statusCode).toBe(409);
      expect(codeOf(full)).toBe('PUBLIC_SLOT_FULL');

      // The guest who holds four may still move to five at seven: their own
      // party is not counted against them — and the server agrees.
      // The guest finds it however they type the code and the number (55 DP24, F15)…
      await guest.claim(booked.code.toLowerCase().replace('-', ' '), '+44 7700 900001');
      await guest.claim(booked.code.slice(3), '07700 900 001');
      // …but only with the WHOLE number: the last four digits, or another number, find nothing.
      expect(await guest.claimRefused(booked.code, '0001')).toBe('PUBLIC_CLAIM_NO_MATCH');
      expect(await guest.claimRefused(booked.code, '07700900002')).toBe('PUBLIC_CLAIM_NO_MATCH');
      const session = await guest.claim(booked.code, '07700900001');
      expect((await guest.availability(day, 4))['19:00']).toBe('full');
      expect((await guest.availability(day, 4, session))['19:00']).toBe('free');
      expect((await guest.change(session, booked.id, { party: 3 })).statusCode).toBe(200);
      expect(codeOf(await guest.change(session, booked.id, { party: 5 }))).toBe('PUBLIC_SLOT_FULL');

      // Cancelling two days ahead is fine; one within the window is not.
      expect((await guest.change(session, booked.id, { status: 'cancelled' })).statusCode).toBe(200);
      await guest.db
        .updateTable(guest.reservations as never)
        .set({ status: 'booked', starts_at: new Date(Date.now() + 60 * 60_000).toISOString().replace('T', ' ').slice(0, 19) } as never)
        .where('id' as never, '=', booked.id as never)
        .execute();
      const late = await guest.change(session, booked.id, { status: 'cancelled' });
      expect(late.statusCode).toBe(409);
      expect(codeOf(late)).toBe('PUBLIC_TOO_LATE');

      // Changing or cancelling a booking sends no mail (wave 1): only the booking with an email did.
      expect(await guest.mail()).toHaveLength(1);

      // The availability ref is never a way to read the bookings themselves.
      const rows = await guest.rows('reservations_availability');
      expect(rows.statusCode).toBe(404);
    }, 90_000);
  });
}
