// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Booking PEOPLE over HTTP, on every engine: the patients' side asking which
 * times are free (one day, or a strip of days), booking one, and hearing why
 * a time cannot be had; a claimed patient moving their own visit without it
 * blocking itself, and cancelling late; the desk asking the same question
 * and learning who would be booked.
 *
 * Nothing is faked below the route: a real source database carries the
 * booking rule as overrides, the endpoints and the key are made the way an
 * app's install makes them, and every answer comes from the composed server.
 * The clock is pinned to Tuesday 28 July 2026, 08:20 in London.
 */
import { randomBytes } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import BetterSqlite3 from 'better-sqlite3';
import { sql } from 'kysely';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AdapterRegistry, type AdapterProvider } from '@adminium/engine/adapter';
import { connectionTenantConfig, createFirstSuperAdmin, createSqliteMetaDb, firstRun, overridesRepo, settingsRepo, snapshotsRepo, type MetaDb } from '@adminium/meta';

import { composeServer } from '../src/compose.js';
import { dsnCryptoFromSecret } from '../src/connections/crypto.js';
import { runIntrospection } from '../src/connections/introspect.js';
import { ConnectionManager } from '../src/connections/manager.js';
import { registerAdapters } from '../src/connections/register-adapters.js';
import { localTimestamp } from '../src/crud/instants.js';
import { wallTimeToInstant } from '../src/crud/venue-time.js';
import { createApplyService } from '../src/llm/apply-service.js';
import { createRunService } from '../src/llm/run-service.js';
import type { MetaStoreHandle } from '../src/meta/store.js';
import { createEndpointService } from '../src/public-api/endpoint-service.js';
import type { PublicEndpointDefinition } from '../src/public-api/endpoint.js';
import { generatePublishableKey, sealPublishableKey } from '../src/public-api/keys.js';
import { createPublicViews } from '../src/public-api/runtime.js';
import { adminPasswordHash, ADMIN_EMAIL, ADMIN_NAME, ADMIN_PASSWORD, login } from './auth-helpers.js';
import { makeEnv, TEST_SECRET } from './helpers.js';

type Dialect = 'sqlite' | 'postgres' | 'mysql';
const POSTGRES_URL = process.env.TEST_POSTGRES_URL;
const MYSQL_URL = process.env.TEST_MYSQL_URL || undefined;
const ORIGIN = 'https://clinic.example.com';
const ZONE = 'Europe/London';
const TUE = '2026-07-28';
const WED = '2026-07-29';
const THU = '2026-07-30';
const FRI = '2026-07-31';

let close: (() => Promise<void>) | null = null;
afterEach(async () => {
  vi.useRealTimers();
  await close?.();
  close = null;
});

function memoryStore(meta: MetaDb): MetaStoreHandle {
  return { meta, url: 'sqlite::memory:', engine: 'sqlite', source: 'embedded', close: async () => Promise.resolve() };
}

/** The practice's tables, as each engine spells them, and a week of data. */
function ddl(dialect: Dialect): string[] {
  const key = dialect === 'postgres' ? 'integer generated by default as identity primary key' : dialect === 'mysql' ? 'int auto_increment primary key' : 'integer primary key';
  const at = dialect === 'postgres' ? 'timestamptz' : dialect === 'mysql' ? 'datetime' : 'timestamp';
  const bool = dialect === 'postgres' ? 'boolean' : 'integer';
  const yes = dialect === 'postgres' ? 'true' : '1';
  const no = dialect === 'postgres' ? 'false' : '0';
  return [
    `create table settings (id ${key}, slot_minutes integer not null, booking_days integer not null, notice_minutes integer not null, cancel_hours integer not null)`,
    `create table opening_hours (id ${key}, weekday varchar(3) not null, opens varchar(5) not null, closes varchar(5) not null, break_start varchar(5), break_end varchar(5))`,
    `create table clinicians (id ${key}, name varchar(40) not null, position integer not null, active ${bool} not null, bookable_online ${bool} not null)`,
    `create table visit_types (id ${key}, name varchar(40) not null, minutes integer not null)`,
    `create table clinician_visit_types (id ${key}, clinician_id integer not null, visit_type_id integer not null, foreign key (clinician_id) references clinicians (id), foreign key (visit_type_id) references visit_types (id))`,
    `create table closures (id ${key}, clinician_id integer, from_date date not null, to_date date not null, foreign key (clinician_id) references clinicians (id))`,
    `create table patients (id ${key}, name varchar(40) not null, mobile varchar(20) not null)`,
    `create table visits (id ${key}, patient_id integer, clinician_id integer, visit_type_id integer not null, starts_at ${at} not null, minutes integer not null default 15, status varchar(16) not null default 'booked', late_cancel ${bool} not null default ${no}, foreign key (patient_id) references patients (id), foreign key (clinician_id) references clinicians (id), foreign key (visit_type_id) references visit_types (id))`,
    'insert into settings (slot_minutes, booking_days, notice_minutes, cancel_hours) values (15, 5, 60, 24)',
    ...['mon', 'tue', 'wed', 'thu', 'fri'].map(
      (weekday) => `insert into opening_hours (weekday, opens, closes, break_start, break_end) values ('${weekday}', '08:30', '17:30', '12:30', '13:15')`,
    ),
    `insert into clinicians (name, position, active, bookable_online) values ('Ada', 1, ${yes}, ${yes})`,
    `insert into clinicians (name, position, active, bookable_online) values ('Ben', 2, ${yes}, ${no})`,
    "insert into visit_types (name, minutes) values ('Routine', 15)",
    "insert into visit_types (name, minutes) values ('Long', 45)",
    'insert into clinician_visit_types (clinician_id, visit_type_id) values (1, 1)',
    'insert into clinician_visit_types (clinician_id, visit_type_id) values (1, 2)',
    'insert into clinician_visit_types (clinician_id, visit_type_id) values (2, 1)',
    `insert into closures (from_date, to_date) values ('${FRI}', '${FRI}')`,
    "insert into patients (name, mobile) values ('Cormac', '07700900001')",
    "insert into patients (name, mobile) values ('Leila', '07700900002')",
  ];
}

/** `handMade`: the key is an operator's, not the app's — only such a key may hold BATCH. */
async function serving(dialect: Dialect, opts: { handMade?: boolean } = {}) {
  const dataDir = await mkdtemp(join(tmpdir(), 'booking-people-'));
  const meta = createSqliteMetaDb({ database: new BetterSqlite3(':memory:') });
  await firstRun(meta);
  const registry = new AdapterRegistry<AdapterProvider>();
  await registerAdapters(registry);
  const manager = new ConnectionManager({ meta, crypto: dsnCryptoFromSecret(TEST_SECRET), registry, metaDsn: null, blockLoopback: false });

  const name = `adminium_book_${randomBytes(4).toString('hex')}`;
  let dsn: string;
  let drop: () => Promise<void> = async () => undefined;
  if (dialect === 'sqlite') {
    const file = join(dataDir, 'clinic.db');
    new BetterSqlite3(file).close();
    dsn = `sqlite:${file}`;
  } else if (dialect === 'postgres') {
    const { Client } = await import('pg');
    const admin = new Client({ connectionString: POSTGRES_URL });
    await admin.connect();
    await admin.query(`CREATE DATABASE ${name}`);
    await admin.end();
    const url = new URL(POSTGRES_URL as string);
    url.pathname = `/${name}`;
    dsn = url.toString();
    drop = async () => {
      const again = new Client({ connectionString: POSTGRES_URL });
      await again.connect();
      await again.query(`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`);
      await again.end();
    };
  } else {
    const mysql = await import('mysql2/promise');
    const admin = await mysql.createConnection(MYSQL_URL as string);
    await admin.query(`CREATE DATABASE \`${name}\``);
    await admin.end();
    const url = new URL(MYSQL_URL as string);
    url.pathname = `/${name}`;
    dsn = url.toString();
    drop = async () => {
      const again = await mysql.createConnection(MYSQL_URL as string);
      await again.query(`DROP DATABASE IF EXISTS \`${name}\``);
      await again.end();
    };
  }
  const connection = await manager.connections.create({ name: 'Clinic', engine: dialect, introspectDsn: dsn, dataDsn: dsn });
  await meta.db.updateTable('adminium_connections').set({ timezone: ZONE }).where('id', '=', connection.id).execute();
  const { db } = await manager.data(connection.id);
  for (const statement of ddl(dialect)) await sql.raw(statement).execute(db);
  await runIntrospection({ manager, meta, connectionId: connection.id });

  const snapshot = (await snapshotsRepo(meta).latest(connection.id))!;
  const tables = (snapshot.schema as { tables: { id: string; name: string }[] }).tables;
  const idOf = (table: string) => tables.find((t) => t.name === table)!.id;
  const visits = idOf('visits');
  const settings = idOf('settings');
  const overrides = overridesRepo(meta);
  await overrides.create({
    connectionId: connection.id,
    op: 'table.booking',
    tableName: visits,
    value: {
      start: 'starts_at',
      minutes: 'minutes',
      resource: 'clinician_id',
      kind: 'visit_type_id',
      countWhere: { column: 'status', values: ['booked', 'checked_in', 'seen'] },
      eligible: {
        table: idOf('clinician_visit_types'),
        resource: 'clinician_id',
        kind: 'visit_type_id',
        order: { table: idOf('clinicians'), column: 'position', active: 'active', public: 'bookable_online' },
      },
      hours: { practice: { table: idOf('opening_hours'), weekday: 'weekday', opens: 'opens', closes: 'closes', breakStart: 'break_start', breakEnd: 'break_end' } },
      closures: { table: idOf('closures'), from: 'from_date', to: 'to_date', resource: 'clinician_id' },
      grid: { table: settings, column: 'slot_minutes' },
      windowDays: { table: settings, column: 'booking_days' },
      noticeMinutes: { table: settings, column: 'notice_minutes' },
      cancel: { hours: { table: settings, column: 'cancel_hours' }, mode: 'flag', flag: 'late_cancel', when: { column: 'status', to: 'cancelled' } },
    },
  });
  // The length a visit takes, copied from its kind.
  await overrides.create({ connectionId: connection.id, op: 'column.copy', tableName: visits, columnName: 'minutes', value: { via: 'visit_type_id', from: 'minutes', mode: 'always' } });

  const runService = createRunService({ meta });
  const composed = await composeServer({
    env: makeEnv({ ADMINIUM_PUBLIC_API_ORIGINS: ORIGIN, HOST: '127.0.0.1', ADMINIUM_SECRET: TEST_SECRET }),
    metaStore: memoryStore(meta),
    manager,
    runService,
    applyService: createApplyService({ meta, runService }),
    allowed: null,
    logger: false,
    telemetry: false,
  });
  await composed.app.ready();
  await settingsRepo(meta).set('publicApi.enabled', true);
  await createFirstSuperAdmin(meta, { email: ADMIN_EMAIL, name: ADMIN_NAME, passwordHash: await adminPasswordHash() });
  const { cookie } = await login(composed.app, ADMIN_EMAIL, ADMIN_PASSWORD);

  const views = createPublicViews(meta);
  const service = createEndpointService({
    meta,
    viewFor: views.viewFor,
    tenantConfigOf: async (id) => (await connectionTenantConfig(meta, id)) ?? undefined,
  });
  const base = {
    filters: [],
    pagination: { default_limit: 50, max_limit: 200, order: 'id.asc' },
    rate_limit: { requests: 600, window: '1m' },
    response: { shape: 'object', envelope: 'data' },
  };
  const endpoints: Record<string, Record<string, unknown>> = {
    visits: {
      ...base,
      source: visits,
      methods: ['POST'],
      select: ['id', 'clinician_id', 'starts_at'],
      writable: ['clinician_id', 'visit_type_id', 'starts_at'],
      auth: { role: 'anon' },
    },
    patients: {
      ...base,
      source: idOf('patients'),
      methods: ['GET'],
      select: ['id', 'name'],
      auth: { role: 'authenticated' },
      identity: { strategy: 'lookup', match: ['mobile'], column: 'id' },
    },
    visits_claimed: {
      ...base,
      source: visits,
      methods: ['GET', 'PATCH'],
      select: ['id', 'starts_at', 'status', 'late_cancel'],
      writable: ['starts_at', 'status'],
      auth: { role: 'authenticated' },
      claim: { column: 'patient_id' },
    },
    visits_availability: { ...base, source: visits, methods: ['GET'], select: ['id'], auth: { role: 'anon' }, kind: 'availability' },
    // Today's visits, on the venue's calendar.
    visits_today: {
      ...base,
      filters: [{ column: 'starts_at', op: 'today' }],
      source: visits,
      methods: ['GET'],
      select: ['id', 'starts_at', 'status'],
      auth: { role: 'authenticated' },
      claim: { column: 'patient_id' },
    },
    // A form a stranger fills in, proved: one row at a time, never a batch.
    visits_proved: {
      ...base,
      source: visits,
      methods: ['POST', 'BATCH'],
      select: ['id'],
      writable: ['clinician_id', 'visit_type_id', 'starts_at'],
      auth: { role: 'anon' },
      human_check: true,
    },
    // A patient may only cancel, and only a booked visit still ahead.
    visits_limited: {
      ...base,
      source: visits,
      methods: ['GET', 'PATCH'],
      select: ['id', 'starts_at', 'status'],
      writable: ['status'],
      writable_values: { status: ['cancelled'] },
      writable_when: { status: ['booked'], starts_at: 'from-now' },
      auth: { role: 'authenticated' },
      claim: { column: 'patient_id' },
    },
  };
  for (const [ref, definition] of Object.entries(endpoints)) {
    await service.saveEndpoint({ connectionId: connection.id, ref, definition: { path: `/${ref}`, ...definition } as PublicEndpointDefinition, origin: 'custom', managedBy: 'clinic' });
  }
  const generated = generatePublishableKey('browser');
  await service.createKey({
    connectionId: connection.id,
    name: 'Clinic · patients',
    access: [
      { ref: 'visits', methods: ['POST'] },
      { ref: 'patients', methods: ['GET'] },
      { ref: 'visits_claimed', methods: ['GET', 'PATCH'] },
      { ref: 'visits_availability', methods: ['GET'] },
      { ref: 'visits_today', methods: ['GET'] },
      { ref: 'visits_limited', methods: ['GET', 'PATCH'] },
      ...(opts.handMade === true ? [{ ref: 'visits_proved', methods: ['POST', 'BATCH'] as ('POST' | 'BATCH')[] }] : []),
    ],
    secret: { prefix: generated.prefix, tokenHash: generated.tokenHash, tokenEncrypted: sealPublishableKey(dsnCryptoFromSecret(TEST_SECRET), generated.token) },
    origins: [],
    kind: 'browser',
    ...(opts.handMade === true ? {} : { managedBy: 'clinic' }),
  });

  close = async () => {
    await composed.app.close();
    await manager.disposeAll().catch(() => undefined);
    await drop();
    await meta.db.destroy();
    await rm(dataDir, { recursive: true, force: true });
  };

  const headers = (session?: string) => ({
    authorization: `Bearer ${generated.token}`,
    origin: ORIGIN,
    ...(session === undefined ? {} : { 'x-adminium-public-session': session }),
  });
  const app = composed.app;
  const get = async (url: string, session?: string) => {
    const res = await app.inject({ method: 'GET', url: `/api/v1/public/availability/visits_availability?${url}`, headers: headers(session) });
    expect(res.statusCode, res.body).toBe(200);
    return (res.json() as { data: Record<string, unknown>[] }).data;
  };
  return {
    db,
    visits,
    /** One day: `{time: state}`. */
    day: async (query: string, session?: string) => Object.fromEntries((await get(query, session)).map((s) => [s['time'], s['state']])),
    strip: (query: string) => get(query),
    raw: (query: string) => app.inject({ method: 'GET', url: `/api/v1/public/availability/visits_availability?${query}`, headers: headers() }),
    book: (values: Record<string, unknown>) => app.inject({ method: 'POST', url: '/api/v1/public/records/visits', headers: headers(), payload: { values } }),
    claim: async (mobile: string) => {
      const res = await app.inject({ method: 'POST', url: '/api/v1/public/claim', headers: headers(), payload: { match: { mobile } } });
      expect(res.statusCode, res.body).toBe(200);
      return (res.json() as { data: { session: string } }).data.session;
    },
    change: (session: string, id: unknown, values: Record<string, unknown>) =>
      app.inject({ method: 'PATCH', url: `/api/v1/public/records/visits_claimed/${String(id)}`, headers: headers(session), payload: { values } }),
    /** The ids an endpoint lists for a session, in order. */
    list: async (ref: string, session: string) => {
      const res = await app.inject({ method: 'GET', url: `/api/v1/public/records/${ref}`, headers: headers(session) });
      expect(res.statusCode, res.body).toBe(200);
      return (res.json() as { data: { id: unknown }[] }).data.map((row) => Number(row.id));
    },
    batch: (ref: string, rows: Record<string, unknown>[]) =>
      app.inject({ method: 'POST', url: `/api/v1/public/records/${ref}/batch`, headers: headers(), payload: { rows } }),
    limited: (session: string, id: unknown, values: Record<string, unknown>) =>
      app.inject({ method: 'PATCH', url: `/api/v1/public/records/visits_limited/${String(id)}`, headers: headers(session), payload: { values } }),
    staff: async (query: string) => {
      const res = await app.inject({ method: 'GET', url: `/api/v1/data/${connection.id}/${visits}/booking-slots?${query}`, headers: { cookie: cookie ?? '' } });
      expect(res.statusCode, res.body).toBe(200);
      return (res.json() as { data: Record<string, unknown>[] }).data;
    },
  };
}

const at = (day: string, hhmm: string) => wallTimeToInstant(`${day} ${hhmm}`, ZONE)!.toISOString();
const MON = '2026-07-27';
const errorOf = (res: { json: () => unknown }) => (res.json() as { error: { code: string; params?: unknown } }).error;

const legs: [Dialect, boolean][] = [
  ['sqlite', true],
  ['postgres', POSTGRES_URL !== undefined],
  ['mysql', MYSQL_URL !== undefined],
];

for (const [dialect, available] of legs) {
  describe.skipIf(!available)(`booking people over the public API on ${dialect}`, () => {
    it('refuses a batch of creates where each must carry a proof', async () => {
      vi.useFakeTimers({ toFake: ['Date'] });
      vi.setSystemTime(wallTimeToInstant(`${TUE} 08:20`, ZONE)!);
      const p = await serving(dialect, { handMade: true });
      const res = await p.batch('visits_proved', [{ clinician_id: 1, visit_type_id: 1, starts_at: at(WED, '09:00') }]);
      expect(res.statusCode, res.body).toBe(403);
      expect(errorOf(res).code).toBe('PUBLIC_PROOF_REQUIRED');
      const rows = await sql.raw<{ n: unknown }>('select count(*) as n from visits').execute(p.db);
      expect(Number(rows.rows[0]!.n)).toBe(0);
    });

    it('reads today on the venue\u2019s clock at every request, and holds a patient\u2019s change to what the endpoint pins', async () => {
      vi.useFakeTimers({ toFake: ['Date'] });
      vi.setSystemTime(wallTimeToInstant(`${TUE} 23:59:50`, ZONE)!);
      const p = await serving(dialect);
      // As each engine keeps a time: an instant, or (MySQL, SQLite) the server's wall clock.
      const spell = (day: string, hhmm: string) => (dialect === 'postgres' ? at(day, hhmm) : localTimestamp(new Date(at(day, hhmm))));
      const seed = async (day: string, hhmm: string, status: string) => {
        await sql.raw(`insert into visits (patient_id, clinician_id, visit_type_id, starts_at, status) values (1, 1, 1, '${spell(day, hhmm)}', '${status}')`).execute(p.db);
        const rows = await sql.raw<{ id: unknown }>('select max(id) as id from visits').execute(p.db);
        return Number(rows.rows[0]!.id);
      };
      const tueSeen = await seed(TUE, '10:00', 'seen');
      const tueBooked = await seed(TUE, '16:00', 'booked');
      const wedEarly = await seed(WED, '09:00', 'booked');
      const wedLate = await seed(WED, '11:00', 'booked');
      const monBooked = await seed(MON, '10:00', 'booked');
      const session = await p.claim('07700900001');

      expect(await p.list('visits_today', session)).toEqual([tueSeen, tueBooked]);
      // Twenty seconds later it is Wednesday. The key's compiled scope is still
      // cached — and the same scope now answers Wednesday's visits.
      vi.setSystemTime(wallTimeToInstant(`${WED} 00:00:10`, ZONE)!);
      expect(await p.list('visits_today', session)).toEqual([wedEarly, wedLate]);

      // Only the values the endpoint names: cancel, never mark seen.
      const seen = await p.limited(session, wedEarly, { status: 'seen' });
      expect(seen.statusCode, seen.body).toBe(400);
      expect(errorOf(seen).code).toBe('PUBLIC_WRITE_REFUSED');
      const cancelled = await p.limited(session, wedEarly, { status: 'cancelled' });
      expect(cancelled.statusCode, cancelled.body).toBe(200);
      // Only from the state it names: a visit already seen, or booked but over, is not changed…
      for (const id of [tueSeen, tueBooked, monBooked]) {
        const refused = await p.limited(session, id, { status: 'cancelled' });
        expect(refused.statusCode, refused.body).toBe(404);
      }
      // …and a cancelled one is not cancelled again.
      expect((await p.limited(session, wedEarly, { status: 'cancelled' })).statusCode).toBe(404);
      // Reads are untouched: every visit still lists, as it is.
      expect(await p.list('visits_limited', session)).toEqual([tueSeen, tueBooked, wedEarly, wedLate, monBooked]);
      const statuses = await sql.raw<{ id: unknown; status: string }>('select id, status from visits order by id').execute(p.db);
      expect(statuses.rows.map((row) => row.status)).toEqual(['seen', 'booked', 'cancelled', 'booked', 'booked']);
    });

    it('offers the times the guard would take, books one, and says why a time cannot be had', async () => {
      vi.useFakeTimers({ toFake: ['Date'] });
      vi.setSystemTime(wallTimeToInstant(`${TUE} 08:20`, ZONE)!);
      const p = await serving(dialect);

      // A routine visit on Wednesday: every quarter hour but lunch, all free.
      const wed = await p.day(`kind=1&resource=any&date=${WED}`);
      const times = Object.keys(wed);
      expect(times[0]).toBe('08:30');
      expect(times.at(-1)).toBe('17:15');
      expect(times).toHaveLength(33);
      for (const lunch of ['12:30', '12:45', '13:00']) expect(times).not.toContain(lunch);
      expect(new Set(Object.values(wed))).toEqual(new Set(['free']));

      const booked = await p.book({ clinician_id: 1, visit_type_id: 1, starts_at: at(WED, '09:00') });
      expect(booked.statusCode, booked.body).toBe(201);
      expect((await p.day(`kind=1&resource=any&date=${WED}`))['09:00']).toBe('full');
      // A 45-minute visit: 08:30 runs into 09:00; 11:45 ends at lunch exactly; none start in or run into lunch.
      const long = await p.day(`kind=2&resource=1&date=${WED}`);
      expect(long).toMatchObject({ '08:30': 'full', '09:15': 'free', '11:45': 'free' });
      expect(Object.keys(long)).not.toContain('12:00');

      // "Anyone" for a guest is never Ben, who is not bookable online.
      const anyone = await p.book({ visit_type_id: 1, starts_at: at(WED, '10:00') });
      expect(anyone.statusCode, anyone.body).toBe(201);
      expect(Number((anyone.json() as { data: { clinician_id: unknown } }).data.clinician_id)).toBe(1);
      expect(await p.strip(`kind=1&resource=2&from=${WED}&days=1`)).toEqual([{ date: WED, open: 0, state: 'closed' }]);

      // Why a time cannot be had, in the patients' side's own words.
      const refused = async (values: Record<string, unknown>) => {
        const res = await p.book(values);
        return { status: res.statusCode, ...errorOf(res) };
      };
      expect(await refused({ clinician_id: 1, visit_type_id: 1, starts_at: at(WED, '09:00') })).toEqual({ status: 409, code: 'PUBLIC_SLOT_FULL', message: 'That time is full.' });
      expect(await refused({ clinician_id: 1, visit_type_id: 1, starts_at: at(FRI, '10:00') })).toMatchObject({ status: 400, code: 'PUBLIC_WRITE_REFUSED', params: { column: 'starts_at', reason: 'closed' } });
      expect(await refused({ clinician_id: 1, visit_type_id: 1, starts_at: at(WED, '09:10') })).toMatchObject({ params: { column: 'starts_at', reason: 'out-of-hours' } });
      expect(await refused({ clinician_id: 1, visit_type_id: 1, starts_at: at(TUE, '08:30') })).toMatchObject({ params: { column: 'starts_at', reason: 'out-of-range' } });
      expect(await refused({ clinician_id: 2, visit_type_id: 1, starts_at: at(WED, '11:00') })).toMatchObject({ params: { column: 'clinician_id', reason: 'not-offered' } });

      // A week: past, today (from an hour ahead), open days, the closure, the weekend.
      const week = await p.strip(`kind=1&resource=any&from=2026-07-27&days=7`);
      expect(week.map((d) => d['state'])).toEqual(['closed', 'open', 'open', 'open', 'closed', 'closed', 'closed']);
      expect(week[1]).toEqual({ date: TUE, open: 29, state: 'open' });
      // Beyond five working days: closed, however many times it has.
      expect((await p.strip(`kind=1&resource=any&from=2026-08-05&days=1`))[0]).toMatchObject({ state: 'closed' });

      // A question in neither form is refused.
      expect((await p.raw('kind=1')).statusCode).toBe(400);
      expect((await p.raw(`date=${WED}&party=2`)).statusCode).toBe(400);
    }, 90_000);

    it('lets a claimed patient move their visit past itself, and nobody else’s', async () => {
      vi.useFakeTimers({ toFake: ['Date'] });
      vi.setSystemTime(wallTimeToInstant(`${TUE} 08:20`, ZONE)!);
      const p = await serving(dialect);
      /** A visit as the desk would have made it, at a wall time on the venue's clock. */
      const insert = async (patient: number, day: string, hhmm: string, minutes = 15, type = 1): Promise<number> => {
        await p.db
          .insertInto(p.visits as never)
          .values({ patient_id: patient, clinician_id: 1, visit_type_id: type, starts_at: dialect === 'sqlite' ? at(day, hhmm) : new Date(at(day, hhmm)), minutes } as never)
          .execute();
        const row = await sql.raw<{ id: unknown }>('select max(id) as id from visits').execute(p.db);
        return Number(row.rows[0]!.id);
      };
      // Cormac's 45-minute visit on Thursday at 10:00; Leila's at 11:00.
      const mine = await insert(1, THU, '10:00', 45, 2);
      const hers = await insert(2, THU, '11:00');
      const session = await p.claim('07700900001');

      const q = `kind=2&resource=1&date=${THU}`;
      expect((await p.day(q))['10:15']).toBe('full');
      // Moving his own: his visit does not block itself — but only with his session.
      expect((await p.day(`${q}&exclude=${String(mine)}`, session))['10:15']).toBe('free');
      expect((await p.day(`${q}&exclude=${String(mine)}`))['10:15']).toBe('full');
      // Naming someone else's visit leaves it counted.
      expect((await p.day(`${q}&exclude=${String(hers)}`, session))['10:15']).toBe('full');

      const moved = await p.change(session, mine, { starts_at: at(THU, '10:15') });
      expect(moved.statusCode, moved.body).toBe(200);
      // Into Leila's time: the guard refuses it.
      const clash = await p.change(session, mine, { starts_at: at(THU, '10:30') });
      expect(errorOf(clash).code).toBe('PUBLIC_SLOT_FULL');

      // Inside the 24-hour window: no moving online, cancelling is flagged late.
      const soon = await insert(1, TUE, '15:00');
      expect(errorOf(await p.change(session, soon, { starts_at: at(TUE, '15:30') })).code).toBe('PUBLIC_TOO_LATE');
      const cancelled = await p.change(session, soon, { status: 'cancelled' });
      expect(cancelled.statusCode, cancelled.body).toBe(200);
      expect([true, 1, '1']).toContain((cancelled.json() as { data: { late_cancel: unknown } }).data.late_cancel);
    }, 90_000);

    it('answers the desk the same question, without the notice, naming who is free', async () => {
      vi.useFakeTimers({ toFake: ['Date'] });
      vi.setSystemTime(wallTimeToInstant(`${TUE} 08:20`, ZONE)!);
      const p = await serving(dialect);
      expect((await p.book({ clinician_id: 1, visit_type_id: 1, starts_at: at(WED, '09:00') })).statusCode).toBe(201);

      const wed = Object.fromEntries((await p.staff(`kind=1&resource=any&date=${WED}`)).map((s) => [s['time'], s]));
      // Ada has 09:00; Ben — desk-only — is free then, and the desk is told so.
      expect(wed['09:00']).toMatchObject({ state: 'free', resource: 2 });
      expect(wed['09:15']).toMatchObject({ state: 'free', resource: 1 });
      // No notice for the desk: 08:30 today is still bookable.
      expect((await p.staff(`kind=1&resource=1&date=${TUE}`))[0]).toEqual({ time: '08:30', state: 'free' });
      expect((await p.staff(`kind=1&resource=any&from=${WED}&days=2`)).map((d) => d['state'])).toEqual(['open', 'open']);
    }, 90_000);
  });
}
