// SPDX-License-Identifier: AGPL-3.0-only
/**
 * THE SCHEMA EDITOR ADDS A COLUMN STAMPED WITH THE CURRENT TIME, ON EVERY ENGINE.
 *
 * SQLite refuses `ALTER TABLE … ADD COLUMN … DEFAULT (datetime('now',
 * 'localtime'))` on a table that holds rows — "Cannot add a column with
 * non-constant default" — required or not. An empty table takes it. So a
 * Studio "add column" given `now` failed on any SQLite table with rows.
 *
 * It is now part of the table's rebuild: the new table carries the default,
 * and the row copy leaves the column out, so every row already there is given
 * the current time. (A table the planner KNOWS is empty keeps its plain ADD
 * COLUMN — `ddl-plan.test.ts`; the server does not count rows, and unknown
 * reads as "has rows".) MySQL's add-empty, fill, then require and Postgres's
 * one ADD COLUMN are pinned beside it.
 *
 * SQLite always runs; Postgres runs with TEST_POSTGRES_URL, MySQL with
 * TEST_MYSQL_URL (`./app-install-harness.ts`).
 */
import { afterEach, describe, expect, it } from 'vitest';
import type { DatabaseModel } from '@adminium/engine';

import { runIntrospection } from '../src/connections/introspect.js';
import { dsnCryptoFromSecret } from '../src/connections/crypto.js';
import { applyServerEdit, planServerEdit } from '../src/schema-ddl/programmatic.js';
import { ENGINES, installHarness, type Dialect, type Harness } from './app-install-harness.js';
import { TEST_SECRET } from './helpers.js';

const CREATE: Record<Dialect, string> = {
  sqlite: 'CREATE TABLE shifts (id integer PRIMARY KEY, note varchar(40))',
  postgres: 'CREATE TABLE shifts (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, note varchar(40))',
  mysql: 'CREATE TABLE shifts (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, note varchar(40))',
};

/** The Studio's "add column": required, the current time. */
const addClosedAt = (model: DatabaseModel) => ({
  addColumns: [
    {
      table: model.tables.find((t) => t.name === 'shifts')!.id,
      column: {
        name: 'closed_at',
        logicalType: 'timestamptz' as const,
        nullable: false,
        default: { kind: 'now' as const },
        maxLength: null,
        numericPrecision: null,
        numericScale: null,
        comment: null,
      },
    },
  ],
});

/** A stored time as milliseconds, read on this server's clock where the column keeps no zone. */
function millis(value: unknown): number {
  if (value instanceof Date) return value.getTime();
  return new Date(String(value).replace(' ', 'T')).getTime();
}

let harness: Harness | null = null;
afterEach(async () => {
  await harness?.close();
  harness = null;
});

describe.each(ENGINES)('adding a required column stamped with the current time, on %s', (dialect, available) => {
  it.skipIf(!available)('stamps the rows already there, then requires it', async () => {
    const h = (harness = await installHarness(dialect));
    await h.run(CREATE[dialect]);
    await h.run(`INSERT INTO shifts (note) VALUES ('first')`);
    await runIntrospection({ manager: h.manager, meta: h.meta, connectionId: h.connectionId });
    const deps = { meta: h.meta, manager: h.manager, crypto: dsnCryptoFromSecret(TEST_SECRET) };

    const plan = await planServerEdit(deps, h.connectionId, addClosedAt, { superAdmin: false });
    expect(plan.refusals).toEqual([]);
    const before = Date.now();
    const applied = await applyServerEdit(deps, h.connectionId, addClosedAt, { superAdmin: false, createdBy: null });
    const after = Date.now();
    expect(applied.steps.map((s) => s.outcome)).toEqual(plan.steps.map(() => 'succeeded'));
    expect(plan.steps.map((s) => [s.kind, s.hazard])).toEqual(
      {
        // The one way SQLite takes a clock default on a table with rows.
        sqlite: [['rebuild-table', 'rewrite']],
        mysql: [
          ['add-column', 'rewrite'],
          ['set-not-null', 'rewrite'],
        ],
        postgres: [['add-column', 'safe']],
      }[dialect],
    );

    const read =
      dialect === 'mysql'
        ? "SELECT note, DATE_FORMAT(closed_at, '%Y-%m-%d %H:%i:%s') AS closed_at FROM shifts"
        : 'SELECT note, closed_at FROM shifts';
    const [first] = await h.rows(read);
    expect(first!['note']).toBe('first');
    const stamped = millis(first!['closed_at']);
    expect(stamped).toBeGreaterThanOrEqual(before - 1000);
    expect(stamped).toBeLessThanOrEqual(after + 1000);

    // Required from now on.
    await expect(h.run(`INSERT INTO shifts (note, closed_at) VALUES ('empty', NULL)`)).rejects.toThrow();
    if (dialect !== 'mysql') {
      // The database stamps a row written without it (MySQL leaves that to Adminium's own writes).
      await h.run(`INSERT INTO shifts (note) VALUES ('second')`);
      const [second] = await h.rows(`SELECT closed_at FROM shifts WHERE note = 'second'`);
      expect(second!['closed_at']).not.toBeNull();
    }
  });
});
