// SPDX-License-Identifier: AGPL-3.0-only
/**
 * GENERATED by scripts/gen-resources.mjs — do not edit by hand.
 * How many texts each deferred group of en-US holds (see ./namespaces.ts).
 */
export const DEFERRED_GROUP_COUNTS = {"common":{"builder":187,"kb":66,"about":74,"team":66},"ui":{"widgets":974,"templates":320,"pages":43}} as const;
