/**
 * The live `widgetRegistry`'s id set, as a **pure, checked-in list**.
 *
 * WHY THIS EXISTS: `./index.ts` builds `widgetRegistry` from the per-family
 * `definitions.ts` modules — component code. The generator leaf
 * (`../generate/index.ts`) and everything downstream of it (the Engine, and
 * through it the server) may not import that (01-architecture.md §2.3; the
 * `engine-no-full-widgets` / `server-no-ui-widgets-charts` dependency-cruiser
 * rules). Yet 04 §8 H1/H4 require generation to know which ids are registered:
 * an unregistered id reaching a stored page renders `widget-missing`, and
 * `composeTemplate`'s whole PENDING-id discipline is only sound when the
 * membership test is actually supplied.
 *
 * So the id set is inverted into data: this list is the leaf-safe mirror the
 * generator defaults to, and `registered-ids.test.ts` fails the moment it drifts
 * from `[...widgetRegistry.keys()]` in either direction. Same "checked-in
 * expectation, gated by a parity test" discipline as
 * `../templates/crosscheck.ts`'s `PENDING_TEMPLATE_WIDGET_IDS` and
 * `../qa/delivered.ts` — register a widget, add it here, and the gate tells you
 * if you forget.
 *
 * Sorted; ids are globally unique (04 §2.1).
 */
export const REGISTERED_WIDGET_IDS: readonly string[] = [
  'accordion-list',
  'activity-feed',
  'ai-chat-panel',
  'alert-banner',
  'attachment-list',
  'auto-insights',
  'autosave-indicator',
  'avatar-stack',
  'block-approval',
  'block-attachments',
  'block-bar-chart',
  'block-contact',
  'block-delivery-stepper',
  'block-discount-codes',
  'block-highlight-box',
  'block-image-placeholder',
  'block-kpi-row',
  'block-late-fees',
  'block-line-chart',
  'block-line-items',
  'block-loyalty-banner',
  'block-multi-currency',
  'block-payment-history',
  'block-qr-pay',
  'block-recurring-banner',
  'block-signature',
  'block-tax-breakdown',
  'block-terms-checkbox',
  'block-totals-summary',
  'block-two-col-table',
  'board-card',
  'breadcrumb',
  'bulk-action-toolbar',
  'calendar-legend-filter',
  'calendar-month',
  'call-widget',
  'capacity-board',
  'card-gallery',
  'chart-anomaly',
  'chart-bar',
  'chart-boxplot',
  'chart-bullet',
  'chart-bump',
  'chart-candlestick',
  'chart-chord',
  'chart-choropleth-grid',
  'chart-cohort-matrix',
  'chart-correlation-matrix',
  'chart-donut',
  'chart-forecast',
  'chart-funnel',
  'chart-heat-month',
  'chart-heatmap-calendar',
  'chart-hexbin',
  'chart-line-area',
  'chart-marimekko',
  'chart-multiline',
  'chart-parallel-coordinates',
  'chart-pareto',
  'chart-radar',
  'chart-radial-bar',
  'chart-ranking-bars',
  'chart-ridgeline',
  'chart-sankey',
  'chart-scatter-bubble',
  'chart-slope',
  'chart-sparkline',
  'chart-stacked-bar-100',
  'chart-stream',
  'chart-sunburst',
  'chart-timeline-lanes',
  'chart-treemap',
  'chart-violin',
  'chart-waterfall',
  'chart-wordcloud',
  'chat-thread',
  'chip-cloud',
  'chip-input',
  'column-mapping-table',
  'command-palette',
  'comparison-matrix',
  'connection-status',
  'connection-string-field',
  'conversation-inbox',
  'data-grid',
  'date-range-picker',
  'day-agenda',
  'detail-key-value',
  'diagnostics-readout',
  'document-canvas',
  'drawer-form',
  'empty-state',
  'export-builder',
  'file-browser',
  'filter-chip-bar',
  'flow-builder',
  'gantt-chart',
  'gauge-arc',
  'gauge-ring',
  'global-search',
  'grouped-summary-table',
  'image-board',
  'inline-compose-card',
  'inline-editable-field',
  'kanban-board',
  'kanban-swimlane-grid',
  'kpi-stat-card',
  'kpi-stat-tile-compact',
  'link-list',
  'load-older-paginator',
  'log-table',
  'map-bubble',
  'map-choropleth-grid',
  'master-list',
  'metric-hero',
  'micro-kpi-subtitle',
  'mini-table',
  'modal-wizard',
  'nav-card',
  'notification-feed',
  'option-cards',
  'org-chart',
  'otp-input',
  'pagination-footer',
  'password-strength-meter',
  'period-comparison',
  'progress-bar',
  'progress-log-console',
  'question-builder',
  'ranked-entity-list',
  'realtime-feed',
  'rule-builder',
  'schedule-matrix',
  'scheduled-jobs-list',
  'schema-tree',
  'segmented-control',
  'shortcuts-panel',
  'sidebar-nav',
  'sparkline-table',
  'stat-pair-card',
  'state-hero',
  'status-banner-hero',
  'status-pill',
  'stepper',
  'tab-bar',
  'table-inclusion-checklist',
  'timeline-vertical',
  'toast-stack',
  'toggle-matrix',
  'toggle-switch-list',
  'top-movers-list',
  'typing-indicator',
  'unread-badge',
  'upcoming-events-list',
  'upload-dropzone',
  'upload-progress-list',
  'usage-meter',
  'validation-issues-list',
  'widget-missing',
];

const REGISTERED = new Set(REGISTERED_WIDGET_IDS);

/** Registry-membership test — the default `ctx.isRegistered` for generation. */
export function isRegisteredWidgetId(widgetId: string): boolean {
  return REGISTERED.has(widgetId);
}
