// SPDX-License-Identifier: AGPL-3.0-only
/**
 * What `PUT …/schema/overrides` will accept as a COLUMN RULE, and what it
 * refuses by name.
 *
 * ─── Why the route checks more than the payload schema ─────────────────────
 *
 * `overridePatchSchema` proves the SHAPE: `kind` is one of six words, `min` is
 * a number. It cannot prove the rule is keepable, because it never sees the
 * column. A `now` fill on a `varchar` column parses perfectly and then writes
 * an ISO string into a name field on every insert; an option list on a column
 * whose values the database already fixes is a second, quieter source of truth
 * that the CHECK constraint will overrule at the worst possible moment.
 *
 * So each rule is checked against the column it names, in the live snapshot,
 * and a refused one comes back as a 422 that says which column and why —
 * never as a rule that is stored, shown in Studio, drawn in the form, and then
 * contradicted by the database.
 */
import type { ColumnModel, DatabaseModel, LogicalType, TableModel } from '@adminium/engine';
import { formulaColumns, formulaExprSchema, type States } from '@adminium/manifest';

/** The lists that live in code rather than the store (D6, Appendix D). */
export const BUILTIN_OPTION_LISTS = ['builtin:countries', 'builtin:us-states', 'builtin:gender'] as const;

const NOW_TYPES: ReadonlySet<LogicalType> = new Set(['date', 'time', 'timestamp', 'timestamptz']);
const UUID_TYPES: ReadonlySet<LogicalType> = new Set(['uuid', 'text', 'varchar']);
const USER_TYPES: ReadonlySet<LogicalType> = new Set(['text', 'varchar', 'uuid', 'integer', 'bigint']);
const NUMERIC_TYPES: ReadonlySet<LogicalType> = new Set(['integer', 'bigint', 'decimal', 'float']);
const TEXTUAL_TYPES: ReadonlySet<LogicalType> = new Set(['text', 'varchar']);
/** Types whose answers cannot be a list: they have their own, or no, vocabulary. */
const UNLISTABLE_TYPES: ReadonlySet<LogicalType> = new Set(['boolean', 'json', 'binary']);

type Value = Record<string, unknown>;

/**
 * The reason this rule cannot be kept for this column, or `null`.
 *
 * One string, in the operator's words — the route turns it into the 422. There
 * is no code vocabulary here on purpose: these are refusals an admin reads once
 * while editing a rule, not something a client branches on.
 */
export function columnRuleIssue(
  op:
    | 'column.default'
    | 'column.options'
    | 'column.required'
    | 'column.validation'
    | 'column.copy'
    | 'column.sequence'
    | 'column.code'
    | 'column.rollup'
    | 'column.venueLocal'
    | 'column.stamp'
    | 'column.format'
    | 'column.formula'
    | 'column.scale'
    | 'column.normalize'
    | 'column.bounds',
  raw: unknown,
  column: ColumnModel,
  model: DatabaseModel,
  /**
   * The workspace's own list keys, which the route reads from the store
   * (phase F). Absent ⇒ only the built-ins exist, which is what a caller with
   * no store — a project file checked offline — can know.
   */
  knownLists?: ReadonlySet<string> | undefined,
): string | null {
  const value = (raw ?? {}) as Value;
  const name = JSON.stringify(column.name);
  switch (op) {
    case 'column.default': {
      if (column.isGenerated) {
        return `${name} is generated by the database, so Adminium cannot fill it.`;
      }
      const kind = String(value['kind']);
      // SQLite stores a timestamp as TEXT and reports it as `text`, so there a
      // text column IS a date column (the same widening `defaultKindAllowed`
      // makes for the designer).
      const dateCapable =
        NOW_TYPES.has(column.logicalType) ||
        (model.dialect === 'sqlite' &&
          (column.logicalType === 'text' || column.logicalType === 'varchar'));
      if (kind === 'now' && !dateCapable) {
        return `A date-and-time default needs a date or timestamp column; ${name} is ${column.logicalType}.`;
      }
      if (kind === 'uuid' && !UUID_TYPES.has(column.logicalType)) {
        return `A unique-id default needs a uuid or text column; ${name} is ${column.logicalType}.`;
      }
      if (kind === 'current-user' && !USER_TYPES.has(column.logicalType)) {
        return `The signed-in user cannot be stored in a ${column.logicalType} column.`;
      }
      if (kind === 'literal' && typeof value['text'] !== 'string') {
        return 'A fixed starting value needs the value itself.';
      }
      if (kind === 'from') {
        const from = value['from'];
        if (from === 'connection.currency') {
          if (!TEXTUAL_TYPES.has(column.logicalType)) return `A currency is three letters: ${name} is ${column.logicalType}.`;
        } else if (typeof from === 'object' && from !== null && 'table' in from) {
          const issue = settingIssue(from as Value, model);
          if (issue !== null) return issue;
        } else if (typeof from !== 'object' || from === null) {
          return 'A value filled from elsewhere names where: the connection\'s currency, a settings column or an add-on setting.';
        }
      }
      // `onUpdate` means "fill it again when the row changes", which only a
      // clock and an actor can answer. On a literal or a uuid it would rewrite
      // the same value, or mint a new key, on every save (plan 33's lesson).
      if (value['onUpdate'] === true && kind !== 'now' && kind !== 'current-user') {
        return 'Only the current time and the signed-in user can be filled in again on every change.';
      }
      return null;
    }

    case 'column.options': {
      if (UNLISTABLE_TYPES.has(column.logicalType)) {
        return `A ${column.logicalType} column cannot have a list of allowed values.`;
      }
      if (column.enumRef !== null) {
        const values = model.enums.find((def) => def.id === column.enumRef)?.values ?? [];
        return (
          `Your database already fixes what ${name} accepts` +
          (values.length > 0 ? ` (${values.join(', ')})` : '') +
          ' — change those values in Studio → Schema → Design.'
        );
      }
      if ('list' in value) {
        const key = String(value['list']);
        // A rule may only name a list that EXISTS: a key nobody defines would
        // be a rule that quietly checks nothing (the write path treats an
        // unresolvable list as no list at all), and the admin would have no way
        // to see that the column they just restricted is not restricted.
        if (!(BUILTIN_OPTION_LISTS as readonly string[]).includes(key) && knownLists?.has(key) !== true) {
          return `There is no list called ${JSON.stringify(key)}.`;
        }
        return null;
      }
      const items = (value['values'] ?? []) as { value: string }[];
      const seen = new Set<string>();
      for (const item of items) {
        if (seen.has(item.value)) return `${JSON.stringify(item.value)} is listed twice.`;
        seen.add(item.value);
      }
      return null;
    }

    case 'column.required': {
      if (column.isGenerated) {
        return `${name} is generated by the database, so nobody fills it in.`;
      }
      return null;
    }

    case 'column.validation': {
      const min = value['min'];
      const max = value['max'];
      if (typeof min === 'number' && typeof max === 'number' && min > max) {
        return 'The smallest value cannot be larger than the largest.';
      }
      const minLength = value['minLength'];
      const maxLength = value['maxLength'];
      if (typeof minLength === 'number' && typeof maxLength === 'number' && minLength > maxLength) {
        return 'The shortest length cannot be larger than the longest.';
      }
      const lengths = typeof minLength === 'number' || typeof maxLength === 'number';
      if (lengths && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A length rule needs a text column; ${name} is ${column.logicalType}.`;
      }
      const bounds = typeof min === 'number' || typeof max === 'number';
      if (bounds && !NUMERIC_TYPES.has(column.logicalType)) {
        return `A smallest or largest value needs a number column; ${name} is ${column.logicalType}.`;
      }
      if (value['format'] !== undefined && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A format rule needs a text column; ${name} is ${column.logicalType}.`;
      }
      return null;
    }

    case 'column.copy': {
      if (column.isGenerated) return `${name} is generated by the database, so Adminium cannot fill it.`;
      const table = model.tables.find((candidate) => candidate.columns.includes(column));
      const via = String(value['via']);
      const from = String(value['from']);
      if (via === column.name) return `${name} cannot be copied through itself.`;
      const relation = model.relations.find(
        (r) => r.through === null && r.from.tableId === table?.id && r.from.columns.length === 1 && r.from.columns[0] === via,
      );
      if (relation === undefined) return `${JSON.stringify(via)} does not link this table to another one.`;
      const target = model.tables.find((candidate) => candidate.id === relation.to.tableId);
      if (target?.columns.some((c) => c.name === from) !== true) {
        return `The linked table has no column ${JSON.stringify(from)}.`;
      }
      return null;
    }

    case 'column.sequence': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} numbers itself, so it takes no running number.`;
      if (!NUMERIC_TYPES.has(column.logicalType) && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A running number needs a number or text column; ${name} is ${column.logicalType}.`;
      }
      if (value['gapless'] === true) {
        if (column.logicalType !== 'integer' && column.logicalType !== 'bigint') {
          return `A number without gaps is a whole number; ${name} is ${column.logicalType}.`;
        }
        const table = model.tables.find((candidate) => candidate.columns.includes(column));
        if (value['scope'] !== undefined && table?.columns.some((c) => c.name === String(value['scope'])) !== true) {
          return `${table?.name ?? 'This table'} has no column ${JSON.stringify(value['scope'])} to number within.`;
        }
        const start = value['startSetting'];
        if (typeof start === 'object' && start !== null && 'table' in start) {
          const issue = settingIssue(start as Value, model);
          if (issue !== null) return issue;
        }
      } else if (value['scope'] !== undefined || value['startSetting'] !== undefined) {
        return 'A running number per parent, or one that starts at a setting, is numbered without gaps.';
      }
      return null;
    }

    case 'column.format': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} is filled by the database, so Adminium cannot write it.`;
      if (!TEXTUAL_TYPES.has(column.logicalType)) return `A number with a prefix needs a text column; ${name} is ${column.logicalType}.`;
      const table = model.tables.find((candidate) => candidate.columns.includes(column));
      const from = table?.columns.find((c) => c.name === String(value['from']));
      if (from === undefined) return `${table?.name ?? 'This table'} has no column ${JSON.stringify(value['from'])} to number from.`;
      if (!NUMERIC_TYPES.has(from.logicalType)) return `${from.name} is not a number, so it cannot be written with a prefix.`;
      const width = String(value['prefix'] ?? '').length + Number(value['pad'] ?? 0);
      if (column.maxLength !== null && column.maxLength < width) return `${name} holds ${String(column.maxLength)} characters, fewer than the prefix and the padding.`;
      const setting = value['prefixSetting'];
      if (typeof setting === 'object' && setting !== null && 'table' in setting) {
        const issue = settingIssue(setting as Value, model);
        if (issue !== null) return issue;
      }
      return null;
    }

    case 'column.formula': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} is filled by the database, so Adminium cannot work it out.`;
      if (!NUMERIC_TYPES.has(column.logicalType) || column.logicalType === 'float') {
        // SQLite keeps every decimal as a REAL, and reports it as float.
        if (!(column.logicalType === 'float' && model.dialect === 'sqlite')) {
          return `A worked-out value needs a decimal or whole-number column; ${name} is ${column.logicalType}.`;
        }
      }
      const parsed = formulaExprSchema.safeParse(value['formula']);
      if (!parsed.success) return 'The formula is not one Adminium can work out.';
      const table = model.tables.find((candidate) => candidate.columns.includes(column));
      for (const ref of formulaColumns(parsed.data)) {
        if (ref === column.name) return `${name} cannot be worked out from itself.`;
        if (table?.columns.some((c) => c.name === ref) !== true) return `${table?.name ?? 'This table'} has no column ${JSON.stringify(ref)} for the formula.`;
      }
      return null;
    }

    case 'column.bounds': {
      // SQLite keeps a date as text, and says so.
      const dated = (c: ColumnModel) => ['date', 'timestamp', 'timestamptz'].includes(c.logicalType) || (model.dialect === 'sqlite' && TEXTUAL_TYPES.has(c.logicalType));
      if (!dated(column)) return `Only a date is kept within dates; ${name} is ${column.logicalType}.`;
      const bound = value['notBefore'] as { column?: unknown; via?: unknown } | undefined;
      if (bound === undefined) return null;
      const table = model.tables.find((candidate) => candidate.columns.includes(column));
      let owner = table;
      if (typeof bound.via === 'string') {
        const relation = model.relations.find((r) => r.through === null && r.from.tableId === table?.id && r.from.columns.length === 1 && r.from.columns[0] === bound.via);
        if (relation === undefined) return `${JSON.stringify(bound.via)} is not a foreign key of ${table?.name ?? 'this table'}.`;
        owner = model.tables.find((candidate) => candidate.id === relation.to.tableId);
      }
      const other = owner?.columns.find((c) => c.name === bound.column);
      if (other === undefined) return `${owner?.name ?? 'That table'} has no column ${JSON.stringify(bound.column)}.`;
      return dated(other) ? null : `${owner?.name ?? 'That table'}.${String(bound.column)} is not a date.`;
    }

    case 'column.normalize': {
      return TEXTUAL_TYPES.has(column.logicalType) ? null : `Only text is stored trimmed or in lower case; ${name} is ${column.logicalType}.`;
    }

    case 'column.scale': {
      const decimal = column.logicalType === 'decimal' || column.logicalType === 'float';
      return decimal ? null : `Decimal places need a decimal column; ${name} is ${column.logicalType}.`;
    }

    case 'column.code': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} numbers itself, so it takes no code.`;
      if (!TEXTUAL_TYPES.has(column.logicalType)) return `A code needs a text column; ${name} is ${column.logicalType}.`;
      const width = String(value['prefix'] ?? '').length + Number(value['length']);
      if (column.maxLength !== null && column.maxLength < width) {
        return `${name} holds ${String(column.maxLength)} characters; this code needs ${String(width)}.`;
      }
      return null;
    }

    case 'column.venueLocal': {
      // SQLite keeps a timestamp as text, and reports it as text.
      const clock =
        column.logicalType === 'timestamp' ||
        column.logicalType === 'timestamptz' ||
        (model.dialect === 'sqlite' && (column.logicalType === 'text' || column.logicalType === 'varchar'));
      return clock ? null : `A venue's clock needs a date-and-time column; ${name} is ${column.logicalType}.`;
    }

    case 'column.stamp': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} is filled by the database, so Adminium cannot stamp it.`;
      const set = value['set'];
      // SQLite keeps a date and a timestamp as text, and reports them as text.
      const sqliteText = model.dialect === 'sqlite' && (column.logicalType === 'text' || column.logicalType === 'varchar');
      const table = model.tables.find((candidate) => candidate.columns.includes(column));
      const dated = typeof set === 'object' && set !== null && 'addDays' in set;
      if (set === 'now' || set === 'today' || dated) {
        const clock = NOW_TYPES.has(column.logicalType) || sqliteText;
        if (!clock) return `A date stamp needs a date or date-and-time column; ${name} is ${column.logicalType}.`;
      } else if (!TEXTUAL_TYPES.has(column.logicalType) && column.logicalType !== 'enum') {
        return `A stamp that names someone needs a text column; ${name} is ${column.logicalType}.`;
      }
      if (typeof set === 'object' && set !== null && 'copy' in set) {
        const source = String((set as { copy: unknown }).copy);
        if (source === column.name) return `A stamp copies another column, not ${name} itself.`;
        if (table?.columns.some((c) => c.name === source) !== true) return `${table?.name ?? 'This table'} has no column ${JSON.stringify(source)} to copy.`;
      }
      if (dated) {
        const days = (set as { addDays: Value }).addDays;
        for (const part of [days['date'], typeof days['days'] === 'string' ? days['days'] : undefined]) {
          if (part !== undefined && table?.columns.some((c) => c.name === String(part)) !== true) {
            return `${table?.name ?? 'This table'} has no column ${JSON.stringify(part)} to count days from.`;
          }
        }
      }
      if (typeof set === 'object' && set !== null && 'hashOf' in set) {
        if (column.maxLength !== null && column.maxLength < 64) return `A fingerprint is 64 characters; ${name} holds ${String(column.maxLength)}.`;
        const hash = (set as { hashOf: Value }).hashOf;
        for (const part of (hash['columns'] as unknown[] | undefined) ?? []) {
          if (table?.columns.some((c) => c.name === String(part)) !== true) return `${table?.name ?? 'This table'} has no column ${JSON.stringify(part)} to fingerprint.`;
        }
        const children = [
          ...(((hash['children'] as Value[] | undefined) ?? [])),
          ...(((hash['linked'] as Value[] | undefined) ?? []).flatMap((link) => [link, ...(((link['children'] as Value[] | undefined) ?? []))])),
        ];
        for (const child of children) {
          if (!model.tables.some((candidate) => candidate.id === String(child['table']))) {
            return `There is no table ${JSON.stringify(child['table'])} to fingerprint.`;
          }
        }
      }
      const triggers = Array.isArray(value['on']) ? (value['on'] as unknown[]) : [value['on']];
      for (const on of triggers) {
        if (typeof on !== 'object' || on === null) continue;
        const watched = String((on as Value)['column']);
        if (watched === column.name) return `A stamp watches another column, not ${name} itself.`;
        if (table !== undefined && !table.columns.some((c) => c.name === watched)) {
          return `${table.name} has no column ${JSON.stringify(watched)} to watch.`;
        }
      }
      return null;
    }

    case 'column.rollup': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} cannot hold a total.`;
      if (!NUMERIC_TYPES.has(column.logicalType)) return `A total needs a number column; ${name} is ${column.logicalType}.`;
      const parent = model.tables.find((candidate) => candidate.columns.includes(column));
      const child = model.tables.find((candidate) => candidate.id === String(value['from']));
      if (child === undefined) return `There is no table ${JSON.stringify(value['from'])} to add up.`;
      const via = String(value['via']);
      const links = model.relations.some(
        (r) =>
          r.through === null &&
          r.from.tableId === child.id &&
          r.to.tableId === parent?.id &&
          r.from.columns.length === 1 &&
          r.from.columns[0] === via,
      );
      if (!links) return `${JSON.stringify(via)} does not link ${child.name} back to this table.`;
      for (const part of [value['sum'], value['times']]) {
        if (part === undefined) continue;
        const counted = child.columns.find((c) => c.name === String(part));
        if (counted === undefined) return `${child.name} has no column ${JSON.stringify(part)}.`;
        if (!NUMERIC_TYPES.has(counted.logicalType)) return `${child.name}.${counted.name} is not a number, so it cannot be added up.`;
      }
      if (value['unlessSet'] !== undefined && !child.columns.some((c) => c.name === String(value['unlessSet']))) {
        return `${child.name} has no column ${JSON.stringify(value['unlessSet'])}.`;
      }
      const where = value['where'] as Value | undefined;
      const filter = where === undefined ? undefined : child.columns.find((c) => c.name === String(where['column']));
      if (where !== undefined && filter === undefined) return `${child.name} has no column ${JSON.stringify(where['column'])} to filter by.`;
      // An empty value equals nothing: a row left empty would drop out of the total unseen.
      if (filter?.nullable === true) return `${child.name}.${filter.name} may be empty, so a row could drop out of the total unseen.`;
      const balance = value['balance'] as Value | undefined;
      if (balance !== undefined) {
        const names = [balance['column'], balance['of'], ...((balance['minus'] as unknown[] | undefined) ?? [])].map(String);
        for (const part of names) {
          const found = parent?.columns.find((c) => c.name === part);
          if (found === undefined) return `${parent?.name ?? 'This table'} has no column ${JSON.stringify(part)} for the balance.`;
          if (!NUMERIC_TYPES.has(found.logicalType)) return `${parent?.name}.${found.name} is not a number, so it cannot be part of a balance.`;
        }
        const own = String(balance['column']);
        if (own === column.name || names.slice(1).includes(own)) return 'The balance is a column of its own, not one it is worked out from.';
        if (parent?.columns.find((c) => c.name === own)?.isGenerated === true) return `${JSON.stringify(own)} is generated by the database.`;
      }
      return null;
    }
  }
}

/** Why a setting a rule reads (`{table, column}` of a settings row, by its id) is not there, or `null`. */
function settingIssue(setting: Value, model: DatabaseModel): string | null {
  const source = model.tables.find((candidate) => candidate.id === String(setting['table']));
  if (source?.columns.some((c) => c.name === String(setting['column'])) !== true) {
    return `There is no column ${JSON.stringify(setting['column'])} in ${JSON.stringify(setting['table'])} to read.`;
  }
  return null;
}

/**
 * Why a table's states cannot be kept, or `null`: the state column, every
 * column a move or the lock names, and every child table it ties to the
 * state (by its id) with the foreign key back, must exist in the live snapshot.
 */
export function statesRuleIssue(raw: unknown, table: TableModel, model: DatabaseModel): string | null {
  // The shape was proved by the store's own schema (`validateOverrideInput`),
  // which knows a table here is its id in the snapshot (`main.studio_lines`).
  const states = (raw ?? {}) as States;
  if (typeof states.column !== 'string' || typeof states.moves !== 'object' || states.moves === null) {
    return 'The states are not written the way Adminium keeps them.';
  }
  const own = (name: string) => table.columns.some((c) => c.name === name);
  const conditions = Object.values(states.moves).flatMap((moves) => moves.flatMap((move) => (typeof move === 'string' ? [] : (move.requires?.where ?? []))));
  for (const name of [states.column, ...(states.lock?.except ?? []), ...(states.onlyLater ?? []), ...conditions.map((c) => c.column)]) {
    if (!own(name)) return `${table.name} has no column ${JSON.stringify(name)}.`;
  }
  const linked = (id: string, via: string) => {
    const child = model.tables.find((candidate) => candidate.id === id);
    if (child === undefined) return `There is no table ${JSON.stringify(id)} to tie to the state.`;
    if (!child.columns.some((c) => c.name === via)) return `${child.name} has no column ${JSON.stringify(via)}.`;
    return null;
  };
  for (const [id, child] of Object.entries(states.children ?? {})) {
    const issue = linked(id, child.via);
    if (issue !== null) return issue;
    for (const name of child.clearOnCreate ?? []) if (!own(name)) return `${table.name} has no column ${JSON.stringify(name)}.`;
  }
  for (const moves of Object.values(states.moves)) {
    for (const move of moves) {
      if (typeof move === 'string') continue;
      for (const id of Object.keys(move.requires?.children ?? {})) {
        if (states.children?.[id] === undefined) return `A move asks for rows of ${JSON.stringify(id)}, which is not tied to the state.`;
      }
    }
  }
  for (const ref of states.lockedWhenReferencedBy ?? []) {
    const issue = linked(ref.table, ref.via);
    if (issue !== null) return issue;
  }
  return null;
}

/**
 * Why a table's booking guard cannot be kept, or `null`. The columns it names
 * must be the table's own, and a setting it reads must be a column of a table
 * that exists.
 */
export function capacityRuleIssue(raw: unknown, table: TableModel, model: DatabaseModel): string | null {
  const value = (raw ?? {}) as Value;
  const own = (name: unknown) => table.columns.find((c) => c.name === String(name));
  for (const key of ['slot', 'amount', 'resource'] as const) {
    if (value[key] === undefined) continue;
    if (own(value[key]) === undefined) return `${table.name} has no column ${JSON.stringify(value[key])}.`;
  }
  const countWhere = value['countWhere'] as { column?: unknown } | undefined;
  if (countWhere !== undefined && own(countWhere.column) === undefined) {
    return `${table.name} has no column ${JSON.stringify(countWhere.column)}.`;
  }
  const amount = own(value['amount']);
  if (amount !== undefined && !NUMERIC_TYPES.has(amount.logicalType)) return `${amount.name} is not a number, so it cannot be counted.`;
  for (const key of ['perSlot', 'slotMinutes', 'windowDays', 'opens', 'closes', 'cancelHours'] as const) {
    const setting = value[key];
    if (typeof setting !== 'object' || setting === null) continue;
    const { table: id, column } = setting as { table: string; column: string };
    const source = model.tables.find((candidate) => candidate.id === id);
    if (source?.columns.some((c) => c.name === column) !== true) return `There is no column ${JSON.stringify(column)} in ${JSON.stringify(id)} to read.`;
  }
  return null;
}

/**
 * Why a table's booking rule cannot be kept, or `null`: every column it names
 * on its own table, and every table and column it reads elsewhere — the link
 * table of who does what, the weekly hours, the closures, the settings row —
 * must exist in the live snapshot. A nested table left unmapped (the app's
 * short name, or none) is caught here, before the guard would query a table
 * that is not there on every booking.
 */
export function bookingRuleIssue(raw: unknown, table: TableModel, model: DatabaseModel): string | null {
  const value = (raw ?? {}) as Value;
  const own = (name: unknown) => table.columns.find((c) => c.name === String(name));
  const ownNames: unknown[] = [value['start'], value['minutes'], value['resource'], value['kind'], (value['countWhere'] as Value | undefined)?.['column']];
  const cancel = value['cancel'] as Value | undefined;
  if (cancel !== undefined) ownNames.push((cancel['when'] as Value | undefined)?.['column'], cancel['flag']);
  for (const name of ownNames) {
    if (name === undefined) continue;
    if (own(name) === undefined) return `${table.name} has no column ${JSON.stringify(name)}.`;
  }
  const minutes = own(value['minutes']);
  if (minutes !== undefined && !NUMERIC_TYPES.has(minutes.logicalType)) {
    return `${minutes.name} is not a number, so it cannot be a length in minutes.`;
  }

  /** The table by its snapshot id, and each of `columns` on it. */
  const elsewhere = (part: unknown, what: string): string | null => {
    if (part === undefined) return null;
    const entry = part as Value;
    const id = String(entry['table'] ?? '');
    const source = model.tables.find((candidate) => candidate.id === id);
    if (source === undefined) return `There is no table ${JSON.stringify(id)} for the ${what} to read.`;
    for (const [key, column] of Object.entries(entry)) {
      if (key === 'table' || typeof column !== 'string') continue;
      if (!source.columns.some((c) => c.name === column)) return `${source.name} has no column ${JSON.stringify(column)} for the ${what}.`;
    }
    return null;
  };
  const eligible = value['eligible'] as Value | undefined;
  const hours = value['hours'] as Value | undefined;
  for (const [part, what] of [
    [eligible === undefined ? undefined : { ...eligible, order: undefined }, 'list of who does what'],
    [eligible?.['order'], 'booking order'],
    [hours?.['practice'], 'opening hours'],
    [hours?.['own'], 'own hours'],
    [value['closures'], 'closures'],
  ] as const) {
    const issue = elsewhere(part, what);
    if (issue !== null) return issue;
  }
  if (eligible === undefined || hours?.['practice'] === undefined) return 'A booking rule names who does what and the opening hours.';

  for (const setting of [value['grid'], value['windowDays'], value['noticeMinutes'], cancel?.['hours']]) {
    if (typeof setting !== 'object' || setting === null) continue;
    const { table: id, column } = setting as { table: string; column: string };
    const source = model.tables.find((candidate) => candidate.id === id);
    if (source?.columns.some((c) => c.name === column) !== true) return `There is no column ${JSON.stringify(column)} in ${JSON.stringify(id)} to read.`;
  }
  return null;
}
