// SPDX-License-Identifier: AGPL-3.0-only
/**
 * What `PUT …/schema/overrides` will accept as a COLUMN RULE, and what it
 * refuses by name.
 *
 * ─── Why the route checks more than the payload schema ─────────────────────
 *
 * `overridePatchSchema` proves the SHAPE: `kind` is one of six words, `min` is
 * a number. It cannot prove the rule is keepable, because it never sees the
 * column. A `now` fill on a `varchar` column parses perfectly and then writes
 * an ISO string into a name field on every insert; an option list on a column
 * whose values the database already fixes is a second, quieter source of truth
 * that the CHECK constraint will overrule at the worst possible moment.
 *
 * So each rule is checked against the column it names, in the live snapshot,
 * and a refused one comes back as a 422 that says which column and why —
 * never as a rule that is stored, shown in Studio, drawn in the form, and then
 * contradicted by the database.
 */
import type { ColumnModel, DatabaseModel, LogicalType, TableModel } from '@adminium/engine';

/** The lists that live in code rather than the store (D6, Appendix D). */
export const BUILTIN_OPTION_LISTS = ['builtin:countries', 'builtin:us-states', 'builtin:gender'] as const;

const NOW_TYPES: ReadonlySet<LogicalType> = new Set(['date', 'time', 'timestamp', 'timestamptz']);
const UUID_TYPES: ReadonlySet<LogicalType> = new Set(['uuid', 'text', 'varchar']);
const USER_TYPES: ReadonlySet<LogicalType> = new Set(['text', 'varchar', 'uuid', 'integer', 'bigint']);
const NUMERIC_TYPES: ReadonlySet<LogicalType> = new Set(['integer', 'bigint', 'decimal', 'float']);
const TEXTUAL_TYPES: ReadonlySet<LogicalType> = new Set(['text', 'varchar']);
/** Types whose answers cannot be a list: they have their own, or no, vocabulary. */
const UNLISTABLE_TYPES: ReadonlySet<LogicalType> = new Set(['boolean', 'json', 'binary']);

type Value = Record<string, unknown>;

/**
 * The reason this rule cannot be kept for this column, or `null`.
 *
 * One string, in the operator's words — the route turns it into the 422. There
 * is no code vocabulary here on purpose: these are refusals an admin reads once
 * while editing a rule, not something a client branches on.
 */
export function columnRuleIssue(
  op:
    | 'column.default'
    | 'column.options'
    | 'column.required'
    | 'column.validation'
    | 'column.copy'
    | 'column.sequence'
    | 'column.code'
    | 'column.rollup'
    | 'column.venueLocal',
  raw: unknown,
  column: ColumnModel,
  model: DatabaseModel,
  /**
   * The workspace's own list keys, which the route reads from the store
   * (phase F). Absent ⇒ only the built-ins exist, which is what a caller with
   * no store — a project file checked offline — can know.
   */
  knownLists?: ReadonlySet<string> | undefined,
): string | null {
  const value = (raw ?? {}) as Value;
  const name = JSON.stringify(column.name);
  switch (op) {
    case 'column.default': {
      if (column.isGenerated) {
        return `${name} is generated by the database, so Adminium cannot fill it.`;
      }
      const kind = String(value['kind']);
      // SQLite stores a timestamp as TEXT and reports it as `text`, so there a
      // text column IS a date column (the same widening `defaultKindAllowed`
      // makes for the designer).
      const dateCapable =
        NOW_TYPES.has(column.logicalType) ||
        (model.dialect === 'sqlite' &&
          (column.logicalType === 'text' || column.logicalType === 'varchar'));
      if (kind === 'now' && !dateCapable) {
        return `A date-and-time default needs a date or timestamp column; ${name} is ${column.logicalType}.`;
      }
      if (kind === 'uuid' && !UUID_TYPES.has(column.logicalType)) {
        return `A unique-id default needs a uuid or text column; ${name} is ${column.logicalType}.`;
      }
      if (kind === 'current-user' && !USER_TYPES.has(column.logicalType)) {
        return `The signed-in user cannot be stored in a ${column.logicalType} column.`;
      }
      if (kind === 'literal' && typeof value['text'] !== 'string') {
        return 'A fixed starting value needs the value itself.';
      }
      // `onUpdate` means "fill it again when the row changes", which only a
      // clock and an actor can answer. On a literal or a uuid it would rewrite
      // the same value, or mint a new key, on every save (plan 33's lesson).
      if (value['onUpdate'] === true && kind !== 'now' && kind !== 'current-user') {
        return 'Only the current time and the signed-in user can be filled in again on every change.';
      }
      return null;
    }

    case 'column.options': {
      if (UNLISTABLE_TYPES.has(column.logicalType)) {
        return `A ${column.logicalType} column cannot have a list of allowed values.`;
      }
      if (column.enumRef !== null) {
        const values = model.enums.find((def) => def.id === column.enumRef)?.values ?? [];
        return (
          `Your database already fixes what ${name} accepts` +
          (values.length > 0 ? ` (${values.join(', ')})` : '') +
          ' — change those values in Studio → Schema → Design.'
        );
      }
      if ('list' in value) {
        const key = String(value['list']);
        // A rule may only name a list that EXISTS: a key nobody defines would
        // be a rule that quietly checks nothing (the write path treats an
        // unresolvable list as no list at all), and the admin would have no way
        // to see that the column they just restricted is not restricted.
        if (!(BUILTIN_OPTION_LISTS as readonly string[]).includes(key) && knownLists?.has(key) !== true) {
          return `There is no list called ${JSON.stringify(key)}.`;
        }
        return null;
      }
      const items = (value['values'] ?? []) as { value: string }[];
      const seen = new Set<string>();
      for (const item of items) {
        if (seen.has(item.value)) return `${JSON.stringify(item.value)} is listed twice.`;
        seen.add(item.value);
      }
      return null;
    }

    case 'column.required': {
      if (column.isGenerated) {
        return `${name} is generated by the database, so nobody fills it in.`;
      }
      return null;
    }

    case 'column.validation': {
      const min = value['min'];
      const max = value['max'];
      if (typeof min === 'number' && typeof max === 'number' && min > max) {
        return 'The smallest value cannot be larger than the largest.';
      }
      const minLength = value['minLength'];
      const maxLength = value['maxLength'];
      if (typeof minLength === 'number' && typeof maxLength === 'number' && minLength > maxLength) {
        return 'The shortest length cannot be larger than the longest.';
      }
      const lengths = typeof minLength === 'number' || typeof maxLength === 'number';
      if (lengths && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A length rule needs a text column; ${name} is ${column.logicalType}.`;
      }
      const bounds = typeof min === 'number' || typeof max === 'number';
      if (bounds && !NUMERIC_TYPES.has(column.logicalType)) {
        return `A smallest or largest value needs a number column; ${name} is ${column.logicalType}.`;
      }
      if (value['format'] !== undefined && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A format rule needs a text column; ${name} is ${column.logicalType}.`;
      }
      return null;
    }

    case 'column.copy': {
      if (column.isGenerated) return `${name} is generated by the database, so Adminium cannot fill it.`;
      const table = model.tables.find((candidate) => candidate.columns.includes(column));
      const via = String(value['via']);
      const from = String(value['from']);
      if (via === column.name) return `${name} cannot be copied through itself.`;
      const relation = model.relations.find(
        (r) => r.through === null && r.from.tableId === table?.id && r.from.columns.length === 1 && r.from.columns[0] === via,
      );
      if (relation === undefined) return `${JSON.stringify(via)} does not link this table to another one.`;
      const target = model.tables.find((candidate) => candidate.id === relation.to.tableId);
      if (target?.columns.some((c) => c.name === from) !== true) {
        return `The linked table has no column ${JSON.stringify(from)}.`;
      }
      return null;
    }

    case 'column.sequence': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} numbers itself, so it takes no running number.`;
      if (!NUMERIC_TYPES.has(column.logicalType) && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A running number needs a number or text column; ${name} is ${column.logicalType}.`;
      }
      return null;
    }

    case 'column.code': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} numbers itself, so it takes no code.`;
      if (!TEXTUAL_TYPES.has(column.logicalType)) return `A code needs a text column; ${name} is ${column.logicalType}.`;
      const width = String(value['prefix'] ?? '').length + Number(value['length']);
      if (column.maxLength !== null && column.maxLength < width) {
        return `${name} holds ${String(column.maxLength)} characters; this code needs ${String(width)}.`;
      }
      return null;
    }

    case 'column.venueLocal': {
      // SQLite keeps a timestamp as text, and reports it as text.
      const clock =
        column.logicalType === 'timestamp' ||
        column.logicalType === 'timestamptz' ||
        (model.dialect === 'sqlite' && (column.logicalType === 'text' || column.logicalType === 'varchar'));
      return clock ? null : `A venue's clock needs a date-and-time column; ${name} is ${column.logicalType}.`;
    }

    case 'column.rollup': {
      if (column.isGenerated || column.isPrimaryKey) return `${name} cannot hold a total.`;
      if (!NUMERIC_TYPES.has(column.logicalType)) return `A total needs a number column; ${name} is ${column.logicalType}.`;
      const parent = model.tables.find((candidate) => candidate.columns.includes(column));
      const child = model.tables.find((candidate) => candidate.id === String(value['from']));
      if (child === undefined) return `There is no table ${JSON.stringify(value['from'])} to add up.`;
      const via = String(value['via']);
      const links = model.relations.some(
        (r) =>
          r.through === null &&
          r.from.tableId === child.id &&
          r.to.tableId === parent?.id &&
          r.from.columns.length === 1 &&
          r.from.columns[0] === via,
      );
      if (!links) return `${JSON.stringify(via)} does not link ${child.name} back to this table.`;
      for (const part of [value['sum'], value['times']]) {
        if (part === undefined) continue;
        const counted = child.columns.find((c) => c.name === String(part));
        if (counted === undefined) return `${child.name} has no column ${JSON.stringify(part)}.`;
        if (!NUMERIC_TYPES.has(counted.logicalType)) return `${child.name}.${counted.name} is not a number, so it cannot be added up.`;
      }
      if (value['unlessSet'] !== undefined && !child.columns.some((c) => c.name === String(value['unlessSet']))) {
        return `${child.name} has no column ${JSON.stringify(value['unlessSet'])}.`;
      }
      return null;
    }
  }
}

/**
 * Why a table's booking guard cannot be kept, or `null`. The columns it names
 * must be the table's own, and a setting it reads must be a column of a table
 * that exists.
 */
export function capacityRuleIssue(raw: unknown, table: TableModel, model: DatabaseModel): string | null {
  const value = (raw ?? {}) as Value;
  const own = (name: unknown) => table.columns.find((c) => c.name === String(name));
  for (const key of ['slot', 'amount', 'resource'] as const) {
    if (value[key] === undefined) continue;
    if (own(value[key]) === undefined) return `${table.name} has no column ${JSON.stringify(value[key])}.`;
  }
  const countWhere = value['countWhere'] as { column?: unknown } | undefined;
  if (countWhere !== undefined && own(countWhere.column) === undefined) {
    return `${table.name} has no column ${JSON.stringify(countWhere.column)}.`;
  }
  const amount = own(value['amount']);
  if (amount !== undefined && !NUMERIC_TYPES.has(amount.logicalType)) return `${amount.name} is not a number, so it cannot be counted.`;
  for (const key of ['perSlot', 'slotMinutes', 'windowDays', 'opens', 'closes', 'cancelHours'] as const) {
    const setting = value[key];
    if (typeof setting !== 'object' || setting === null) continue;
    const { table: id, column } = setting as { table: string; column: string };
    const source = model.tables.find((candidate) => candidate.id === id);
    if (source?.columns.some((c) => c.name === column) !== true) return `There is no column ${JSON.stringify(column)} in ${JSON.stringify(id)} to read.`;
  }
  return null;
}
