// SPDX-License-Identifier: AGPL-3.0-only
/**
 * What `PUT …/schema/overrides` will accept as a COLUMN RULE (plan 50 §3.4,
 * §5).
 *
 * ─── Why the route checks more than the payload schema ─────────────────────
 *
 * `overridePatchSchema` proves the SHAPE: `kind` is one of six words, `min` is
 * a number. It cannot prove the rule is keepable, because it never sees the
 * column. A `now` fill on a `varchar` column parses perfectly and then writes
 * an ISO string into a name field on every insert; an option list on a column
 * whose values the database already fixes is a second, quieter source of truth
 * that the CHECK constraint will overrule at the worst possible moment.
 *
 * So each rule is checked against the column it names, in the live snapshot,
 * and a refused one comes back as a 422 that says which column and why —
 * never as a rule that is stored, shown in Studio, drawn in the form, and then
 * contradicted by the database.
 */
import type { ColumnModel, DatabaseModel, LogicalType } from '@adminium/engine';

/** The lists that live in code rather than the store (D6, Appendix D). */
export const BUILTIN_OPTION_LISTS = ['builtin:countries', 'builtin:us-states', 'builtin:gender'] as const;

const NOW_TYPES: ReadonlySet<LogicalType> = new Set(['date', 'time', 'timestamp', 'timestamptz']);
const UUID_TYPES: ReadonlySet<LogicalType> = new Set(['uuid', 'text', 'varchar']);
const USER_TYPES: ReadonlySet<LogicalType> = new Set(['text', 'varchar', 'uuid', 'integer', 'bigint']);
const NUMERIC_TYPES: ReadonlySet<LogicalType> = new Set(['integer', 'bigint', 'decimal', 'float']);
const TEXTUAL_TYPES: ReadonlySet<LogicalType> = new Set(['text', 'varchar']);
/** Types whose answers cannot be a list: they have their own, or no, vocabulary. */
const UNLISTABLE_TYPES: ReadonlySet<LogicalType> = new Set(['boolean', 'json', 'binary']);

type Value = Record<string, unknown>;

/**
 * The reason this rule cannot be kept for this column, or `null`.
 *
 * One string, in the operator's words — the route turns it into the 422. There
 * is no code vocabulary here on purpose: these are refusals an admin reads once
 * while editing a rule, not something a client branches on.
 */
export function columnRuleIssue(
  op: 'column.default' | 'column.options' | 'column.required' | 'column.validation',
  raw: unknown,
  column: ColumnModel,
  model: DatabaseModel,
  /**
   * The workspace's own list keys, which the route reads from the store
   * (phase F). Absent ⇒ only the built-ins exist, which is what a caller with
   * no store — a project file checked offline — can know.
   */
  knownLists?: ReadonlySet<string> | undefined,
): string | null {
  const value = (raw ?? {}) as Value;
  const name = JSON.stringify(column.name);
  switch (op) {
    case 'column.default': {
      if (column.isGenerated) {
        return `${name} is generated by the database, so Adminium cannot fill it.`;
      }
      const kind = String(value['kind']);
      // SQLite stores a timestamp as TEXT and reports it as `text`, so there a
      // text column IS a date column (the same widening `defaultKindAllowed`
      // makes for the designer).
      const dateCapable =
        NOW_TYPES.has(column.logicalType) ||
        (model.dialect === 'sqlite' &&
          (column.logicalType === 'text' || column.logicalType === 'varchar'));
      if (kind === 'now' && !dateCapable) {
        return `A date-and-time default needs a date or timestamp column; ${name} is ${column.logicalType}.`;
      }
      if (kind === 'uuid' && !UUID_TYPES.has(column.logicalType)) {
        return `A unique-id default needs a uuid or text column; ${name} is ${column.logicalType}.`;
      }
      if (kind === 'current-user' && !USER_TYPES.has(column.logicalType)) {
        return `The signed-in user cannot be stored in a ${column.logicalType} column.`;
      }
      if (kind === 'literal' && typeof value['text'] !== 'string') {
        return 'A fixed starting value needs the value itself.';
      }
      // `onUpdate` means "fill it again when the row changes", which only a
      // clock and an actor can answer. On a literal or a uuid it would rewrite
      // the same value, or mint a new key, on every save (plan 33's lesson).
      if (value['onUpdate'] === true && kind !== 'now' && kind !== 'current-user') {
        return 'Only the current time and the signed-in user can be filled in again on every change.';
      }
      return null;
    }

    case 'column.options': {
      if (UNLISTABLE_TYPES.has(column.logicalType)) {
        return `A ${column.logicalType} column cannot have a list of allowed values.`;
      }
      if (column.enumRef !== null) {
        const values = model.enums.find((def) => def.id === column.enumRef)?.values ?? [];
        return (
          `Your database already fixes what ${name} accepts` +
          (values.length > 0 ? ` (${values.join(', ')})` : '') +
          ' — change those values in Studio → Schema → Design.'
        );
      }
      if ('list' in value) {
        const key = String(value['list']);
        // A rule may only name a list that EXISTS: a key nobody defines would
        // be a rule that quietly checks nothing (the write path treats an
        // unresolvable list as no list at all), and the admin would have no way
        // to see that the column they just restricted is not restricted.
        if (!(BUILTIN_OPTION_LISTS as readonly string[]).includes(key) && knownLists?.has(key) !== true) {
          return `There is no list called ${JSON.stringify(key)}.`;
        }
        return null;
      }
      const items = (value['values'] ?? []) as { value: string }[];
      const seen = new Set<string>();
      for (const item of items) {
        if (seen.has(item.value)) return `${JSON.stringify(item.value)} is listed twice.`;
        seen.add(item.value);
      }
      return null;
    }

    case 'column.required': {
      if (column.isGenerated) {
        return `${name} is generated by the database, so nobody fills it in.`;
      }
      return null;
    }

    case 'column.validation': {
      const min = value['min'];
      const max = value['max'];
      if (typeof min === 'number' && typeof max === 'number' && min > max) {
        return 'The smallest value cannot be larger than the largest.';
      }
      const minLength = value['minLength'];
      const maxLength = value['maxLength'];
      if (typeof minLength === 'number' && typeof maxLength === 'number' && minLength > maxLength) {
        return 'The shortest length cannot be larger than the longest.';
      }
      const lengths = typeof minLength === 'number' || typeof maxLength === 'number';
      if (lengths && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A length rule needs a text column; ${name} is ${column.logicalType}.`;
      }
      const bounds = typeof min === 'number' || typeof max === 'number';
      if (bounds && !NUMERIC_TYPES.has(column.logicalType)) {
        return `A smallest or largest value needs a number column; ${name} is ${column.logicalType}.`;
      }
      if (value['format'] !== undefined && !TEXTUAL_TYPES.has(column.logicalType)) {
        return `A format rule needs a text column; ${name} is ${column.logicalType}.`;
      }
      return null;
    }
  }
}
