import {
  Button,
  Card,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
  EmptyState,
  IconButton,
  IconTile,
  Popover,
  PopoverContent,
  PopoverTrigger,
  Spinner,
} from '@adminium/ui';
import { AlertTriangle, EllipsisVertical, Info, RotateCcw } from 'lucide-react';
import type { ReactNode } from 'react';
import { useMaybeT } from '@adminium/i18n/react';

import { SkeletonSilhouette } from './SkeletonSilhouette.js';
import { WidgetErrorBoundary } from './WidgetErrorBoundary.js';
import type { WidgetSkeleton } from '../registry/types.js';

/**
 * WidgetFrame — the universal wrapper every grid-placed widget renders inside
 * (04-widget-registry.md §4). It owns chrome (header: title, info popover,
 * kebab menu slot, drag-grip slot) and the four states, so widget components
 * only ever render the LOADED state.
 */
export type WidgetFrameState = 'loaded' | 'skeleton' | 'empty' | 'error';

export interface WidgetFrameEmptyContent {
  icon?: ReactNode;
  title?: ReactNode;
  body?: ReactNode;
}

export interface WidgetFrameProps {
  /** Which of the four states to render (04 §4 table). */
  state: WidgetFrameState;
  /** Header title (config or auto-generated by the Engine). */
  title?: ReactNode | undefined;
  /** Info-popover content (descriptionKey text, binding summary, last refreshed). */
  info?: ReactNode | undefined;
  /** Kebab DropdownMenu items (Refresh · Edit · Duplicate · Export · Remove). */
  menu?: ReactNode | undefined;
  /**
   * Drag-grip slot at inline-start of the header — render prop so the M7
   * dashboard grid can hand in its dnd-kit handle; only passed in edit mode.
   */
  dragGrip?: ReactNode | (() => ReactNode) | undefined;
  /** Silhouette for the skeleton state / lazy fallback (definition.skeleton). */
  skeleton?: WidgetSkeleton | undefined;
  /** Empty-state copy override (config.emptyState); default "No data for range". */
  empty?: WidgetFrameEmptyContent | undefined;
  /** Localized error message (never raw SQL/driver text — 04 §4). */
  errorMessage?: ReactNode | undefined;
  /** Retry button handler — re-runs the query. Also invoked after a render-error reset. */
  onRetry?: (() => void) | undefined;
  /** Render-throw hook (audit logging). */
  onRenderError?: ((error: Error) => void) | undefined;
  /** Stale-while-revalidate: keep `loaded`, show a small header spinner (04 §4). */
  refetching?: boolean;
  /**
   * Frameless variant for `placement: 'page'` widgets — states only, no card
   * chrome (04 §4). `inline`/`overlay` widgets skip WidgetFrame entirely.
   */
  frameless?: boolean;
  testId?: string | undefined;
  /** The loaded widget component (rendered inside an error boundary). */
  children?: ReactNode;
}

/**
 * Config `emptyState.titleKey`/`bodyKey` values are i18n key PATHS
 * (`widgets.<family>.<widget>.emptyTitle`); legacy/host configs may carry plain
 * copy in the same slots. Key-shaped values resolve through the bundle;
 * anything else renders verbatim, exactly as before the translator existed.
 */
const EMPTY_STATE_KEY_RE = /^widgets\.[A-Za-z0-9_.]+$/;

/** Last-resort English for a bundle-less key path: 'widgets.charts.bullet.emptyTitle' → 'Empty title'. */
function humanizeKeyLeaf(key: string): string {
  const leaf = key.slice(key.lastIndexOf('.') + 1);
  const words = leaf
    .replace(/[_-]+/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .toLowerCase()
    .trim();
  return words === '' ? key : words.charAt(0).toUpperCase() + words.slice(1);
}

function ErrorBody({ message, onRetry }: { message: ReactNode; onRetry?: (() => void) | undefined }) {
  const t = useMaybeT();
  return (
    <div role="alert" className="flex flex-col items-center gap-3 px-4 py-8 text-center compact:py-6">
      <IconTile tone="danger" size="lg" icon={<AlertTriangle />} />
      <p className="max-w-[320px] text-body-sm text-fg-muted">{message}</p>
      {onRetry === undefined ? null : (
        <Button size="sm" variant="secondary" iconLeft={<RotateCcw />} onClick={onRetry}>
          {t('ui:action.retry', 'Retry')}
        </Button>
      )}
    </div>
  );
}

export function WidgetFrame({
  state,
  title,
  info,
  menu,
  dragGrip,
  skeleton = 'card',
  empty,
  errorMessage,
  onRetry,
  onRenderError,
  refetching = false,
  frameless = false,
  testId,
  children,
}: WidgetFrameProps) {
  const t = useMaybeT();
  const grip = typeof dragGrip === 'function' ? dragGrip() : dragGrip;
  const hasHeader =
    title !== undefined || info !== undefined || menu !== undefined || grip !== undefined;

  // Empty-state translator: key-shaped config copy resolves via the bundle
  // (humanized-leaf English when the key has no entry); plain copy passes through.
  const localizeEmpty = (value: ReactNode): ReactNode =>
    typeof value === 'string' && EMPTY_STATE_KEY_RE.test(value)
      ? // i18n-dynamic-key: the key IS the runtime value — a host/tenant-authored
        // `emptyState.titleKey` naming any widget's empty-state leaf. The frame is
        // generic over every widget in the registry, so the set is not enumerable
        // here; `ui:` only selects the namespace, and `humanizeKeyLeaf` keeps a
        // dangling key from surfacing as a raw dotted string.
        t(`ui:${value}`, humanizeKeyLeaf(value))
      : value;

  const body = (() => {
    switch (state) {
      case 'skeleton':
        return <SkeletonSilhouette variant={skeleton} />;
      case 'empty':
        return (
          <EmptyState
            compact
            preset="no-data"
            {...(empty?.icon !== undefined ? { icon: empty.icon } : {})}
            title={localizeEmpty(empty?.title) ?? t('ui:frame.emptyTitle', 'No data for range')}
            {...(empty?.body !== undefined ? { body: localizeEmpty(empty.body) } : {})}
          />
        );
      case 'error':
        return (
          <ErrorBody
            message={errorMessage ?? t('ui:frame.loadError', 'Something went wrong loading this widget.')}
            onRetry={onRetry}
          />
        );
      case 'loaded':
        return (
          <WidgetErrorBoundary
            onError={onRenderError === undefined ? undefined : (error) => onRenderError(error)}
            fallback={(error, reset) => (
              <ErrorBody
                message={errorMessage ?? error.message ?? t('ui:frame.renderError', 'This widget failed to render.')}
                onRetry={() => {
                  reset();
                  onRetry?.();
                }}
              />
            )}
          >
            {children}
          </WidgetErrorBoundary>
        );
    }
  })();

  const content = (
    <>
      {hasHeader && (
        <header className="flex min-h-10 items-center gap-1.5 px-4 pt-3 compact:px-3 compact:pt-2">
          {grip}
          <h3 className="min-w-0 flex-1 truncate text-body-sm font-semibold text-fg">{title}</h3>
          {refetching && <Spinner size="sm" label={t('ui:frame.refreshing', 'Refreshing')} className="text-fg-muted" />}
          {info !== undefined && (
            <Popover>
              <PopoverTrigger asChild>
                <IconButton size="sm" label={t('ui:frame.infoLabel', 'Widget info')}>
                  <Info size={14} />
                </IconButton>
              </PopoverTrigger>
              <PopoverContent align="end" className="max-w-72 text-body-sm text-fg-muted">
                {info}
              </PopoverContent>
            </Popover>
          )}
          {menu !== undefined && (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <IconButton size="sm" label={t('ui:frame.menuLabel', 'Widget menu')}>
                  <EllipsisVertical size={14} />
                </IconButton>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">{menu}</DropdownMenuContent>
            </DropdownMenu>
          )}
        </header>
      )}
      <div className="min-h-0 flex-1">{body}</div>
    </>
  );

  if (frameless) {
    return (
      <section data-widget-frame data-state={state} data-testid={testId} className="flex h-full flex-col">
        {content}
      </section>
    );
  }
  return (
    <Card asChild padded={false}>
      <section data-widget-frame data-state={state} data-testid={testId} className="flex h-full flex-col overflow-hidden">
        {content}
      </section>
    </Card>
  );
}
