import {
  Button,
  Card,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
  EmptyState,
  IconButton,
  IconTile,
  Popover,
  PopoverContent,
  PopoverTrigger,
  Spinner,
} from '@adminium/ui';
import { AlertTriangle, EllipsisVertical, Info, RotateCcw } from 'lucide-react';
import type { ReactNode } from 'react';

import { SkeletonSilhouette } from './SkeletonSilhouette.js';
import { WidgetErrorBoundary } from './WidgetErrorBoundary.js';
import type { WidgetSkeleton } from '../registry/types.js';

/**
 * WidgetFrame — the universal wrapper every grid-placed widget renders inside
 * (04-widget-registry.md §4). It owns chrome (header: title, info popover,
 * kebab menu slot, drag-grip slot) and the four states, so widget components
 * only ever render the LOADED state.
 */
export type WidgetFrameState = 'loaded' | 'skeleton' | 'empty' | 'error';

export interface WidgetFrameEmptyContent {
  icon?: ReactNode;
  title?: ReactNode;
  body?: ReactNode;
}

export interface WidgetFrameProps {
  /** Which of the four states to render (04 §4 table). */
  state: WidgetFrameState;
  /** Header title (config or auto-generated by the Engine). */
  title?: ReactNode | undefined;
  /** Info-popover content (descriptionKey text, binding summary, last refreshed). */
  info?: ReactNode | undefined;
  /** Kebab DropdownMenu items (Refresh · Edit · Duplicate · Export · Remove). */
  menu?: ReactNode | undefined;
  /**
   * Drag-grip slot at inline-start of the header — render prop so the M7
   * dashboard grid can hand in its dnd-kit handle; only passed in edit mode.
   */
  dragGrip?: ReactNode | (() => ReactNode) | undefined;
  /** Silhouette for the skeleton state / lazy fallback (definition.skeleton). */
  skeleton?: WidgetSkeleton | undefined;
  /** Empty-state copy override (config.emptyState); default "No data for range". */
  empty?: WidgetFrameEmptyContent | undefined;
  /** Localized error message (never raw SQL/driver text — 04 §4). */
  errorMessage?: ReactNode | undefined;
  /** Retry button handler — re-runs the query. Also invoked after a render-error reset. */
  onRetry?: (() => void) | undefined;
  /** Render-throw hook (audit logging). */
  onRenderError?: ((error: Error) => void) | undefined;
  /** Stale-while-revalidate: keep `loaded`, show a small header spinner (04 §4). */
  refetching?: boolean;
  /**
   * Frameless variant for `placement: 'page'` widgets — states only, no card
   * chrome (04 §4). `inline`/`overlay` widgets skip WidgetFrame entirely.
   */
  frameless?: boolean;
  testId?: string | undefined;
  /** The loaded widget component (rendered inside an error boundary). */
  children?: ReactNode;
}

function ErrorBody({ message, onRetry }: { message: ReactNode; onRetry?: (() => void) | undefined }) {
  return (
    <div role="alert" className="flex flex-col items-center gap-3 px-4 py-8 text-center compact:py-6">
      <IconTile tone="danger" size="lg" icon={<AlertTriangle />} />
      <p className="max-w-[320px] text-body-sm text-fg-muted">{message}</p>
      {onRetry === undefined ? null : (
        <Button size="sm" variant="secondary" iconLeft={<RotateCcw />} onClick={onRetry}>
          Retry
        </Button>
      )}
    </div>
  );
}

export function WidgetFrame({
  state,
  title,
  info,
  menu,
  dragGrip,
  skeleton = 'card',
  empty,
  errorMessage,
  onRetry,
  onRenderError,
  refetching = false,
  frameless = false,
  testId,
  children,
}: WidgetFrameProps) {
  const grip = typeof dragGrip === 'function' ? dragGrip() : dragGrip;
  const hasHeader =
    title !== undefined || info !== undefined || menu !== undefined || grip !== undefined;

  const body = (() => {
    switch (state) {
      case 'skeleton':
        return <SkeletonSilhouette variant={skeleton} />;
      case 'empty':
        return (
          <EmptyState
            compact
            preset="no-data"
            {...(empty?.icon !== undefined ? { icon: empty.icon } : {})}
            title={empty?.title ?? 'No data for range'}
            {...(empty?.body !== undefined ? { body: empty.body } : {})}
          />
        );
      case 'error':
        return <ErrorBody message={errorMessage ?? 'Something went wrong loading this widget.'} onRetry={onRetry} />;
      case 'loaded':
        return (
          <WidgetErrorBoundary
            onError={onRenderError === undefined ? undefined : (error) => onRenderError(error)}
            fallback={(error, reset) => (
              <ErrorBody
                message={errorMessage ?? error.message ?? 'This widget failed to render.'}
                onRetry={() => {
                  reset();
                  onRetry?.();
                }}
              />
            )}
          >
            {children}
          </WidgetErrorBoundary>
        );
    }
  })();

  const content = (
    <>
      {hasHeader && (
        <header className="flex min-h-10 items-center gap-1.5 px-4 pt-3 compact:px-3 compact:pt-2">
          {grip}
          <h3 className="min-w-0 flex-1 truncate text-body-sm font-semibold text-fg">{title}</h3>
          {refetching && <Spinner size="sm" label="Refreshing" className="text-fg-muted" />}
          {info !== undefined && (
            <Popover>
              <PopoverTrigger asChild>
                <IconButton size="sm" label="Widget info">
                  <Info size={14} />
                </IconButton>
              </PopoverTrigger>
              <PopoverContent align="end" className="max-w-72 text-body-sm text-fg-muted">
                {info}
              </PopoverContent>
            </Popover>
          )}
          {menu !== undefined && (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <IconButton size="sm" label="Widget menu">
                  <EllipsisVertical size={14} />
                </IconButton>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">{menu}</DropdownMenuContent>
            </DropdownMenu>
          )}
        </header>
      )}
      <div className="min-h-0 flex-1">{body}</div>
    </>
  );

  if (frameless) {
    return (
      <section data-widget-frame data-state={state} data-testid={testId} className="flex h-full flex-col">
        {content}
      </section>
    );
  }
  return (
    <Card asChild padded={false}>
      <section data-widget-frame data-state={state} data-testid={testId} className="flex h-full flex-col overflow-hidden">
        {content}
      </section>
    </Card>
  );
}
