/**
 * `domain` family public surface (annex §13) — the two M7 exit-criteria widgets
 * (`org-chart`, `gantt-chart`) plus their registry metadata and pure geometry.
 * Component code is also reachable through each definition's `lazy()` ref, so
 * the registry still emits one chunk per family (04 §2.3); this barrel is for
 * direct template/story composition and tests. Registry metadata lives in
 * `domain-track.definitions.ts`.
 *
 * TRACK BUILDER (M7 Wave 4) added the §13 DOCUMENT half below: `document-canvas`
 * and its 22-block shared library. The ops/billing/API cards land beside them.
 */
export {
  OrgChart,
  OrgChartWidget,
  orgChartConfigSchema,
  orgChartDemoData,
  type OrgChartConfig,
  type OrgChartProps,
} from './OrgChart.js';
export {
  GanttChart,
  GanttChartWidget,
  ganttChartConfigSchema,
  ganttChartDemoData,
  ganttRowsOf,
  type GanttChartConfig,
  type GanttChartProps,
} from './GanttChart.js';
export { GANTT_DEMO_TODAY_MS } from './domain-config.js';
export {
  DAY_MS,
  DOMAIN_DEMO_EPOCH,
  buildOrgTree,
  categoryTone,
  countNodes,
  dayOffset,
  dayToPercent,
  daysToPercent,
  groupSpan,
  layoutOrgTree,
  mulberry32,
  orgRootsOf,
  parseDateMs,
  toGanttModel,
  toneOf,
  weekTicks,
  type GanttFieldMap,
  type GanttModelOptions,
  type OrgConnector,
  type OrgFieldMap,
  type OrgLayout,
  type OrgLayoutNode,
  type OrgLayoutOptions,
} from './domain-lib.js';
export type {
  GanttData,
  GanttGroup,
  GanttModel,
  GanttTask,
  OrgNode,
  OrgNodeMeta,
  OrgTreeData,
} from './domain-types.js';
export {
  domainTrackDefinitions,
  ganttChartDefinition,
  orgChartDefinition,
} from './domain-track.definitions.js';

// ── TRACK BUILDER (M7 Wave 4): document-canvas + the 22-block vocabulary ─────

export { DocumentCanvasWidget, type DocumentCanvasConfig } from './DocumentCanvas.js';
export {
  BlockDiscountCodesWidget,
  BlockLateFeesWidget,
  BlockLineItemsWidget,
  BlockMultiCurrencyWidget,
  BlockPaymentHistoryWidget,
  BlockQrPayWidget,
  BlockTaxBreakdownWidget,
  BlockTotalsSummaryWidget,
} from './BlockFinancial.js';
export {
  BlockAttachmentsWidget,
  BlockBarChartWidget,
  BlockImagePlaceholderWidget,
  BlockKpiRowWidget,
  BlockLineChartWidget,
  BlockTwoColTableWidget,
} from './BlockReport.js';
export {
  BlockApprovalWidget,
  BlockDeliveryStepperWidget,
  BlockLoyaltyBannerWidget,
  BlockRecurringBannerWidget,
  BlockSignatureWidget,
  BlockTermsCheckboxWidget,
} from './BlockStatus.js';
export { BlockContactWidget, BlockHighlightBoxWidget } from './BlockContent.js';
export { BlockCallout, BlockEmpty, BlockSection, MoneyRow, fillTemplate } from './BlockShell.js';
export {
  BLOCK_DAY_MS,
  BLOCK_DEMO_EPOCH,
  BLOCK_IDS,
  DOC_TYPES,
  DOC_TYPE_BLOCKS,
  blockBindingSourceOf,
  blockDataOf,
  blockOrderOf,
  categoricalData,
  categoricalItemsOf,
  computeTotals,
  docTypeOf,
  formatBlockDate,
  formatBlockMoney,
  formatBlockNumber,
  formatBlockRate,
  formatBlockSize,
  isBlockId,
  lineItemsOf,
  maskMethod,
  moveBlock,
  rowData,
  rowOf,
  rowsData,
  rowsOf,
  round2,
  twoColRowsOf,
  type BlockBindingSource,
  type BlockId,
} from './block-lib.js';
export type {
  BlockApproval,
  BlockAttachment,
  BlockContact,
  BlockDiscountCode,
  BlockFxLine,
  BlockHighlight,
  BlockImagePlaceholder,
  BlockKpi,
  BlockLateFees,
  BlockLoyalty,
  BlockMultiCurrency,
  BlockPayment,
  BlockQrPay,
  BlockRecurring,
  BlockSignature,
  BlockStep,
  BlockTaxLine,
  BlockTerms,
  BlockTwoColRow,
  CategoricalData,
  DocBlockInstance,
  DocData,
  DocLineItem,
  DocRates,
  DocRecord,
  DocTotals,
  DocType,
  RowData,
  RowsData,
} from './block-types.js';
export {
  blockApprovalConfigSchema,
  blockApprovalDemoData,
  blockAttachmentsConfigSchema,
  blockAttachmentsDemoData,
  blockBarChartConfigSchema,
  blockBarChartDemoData,
  blockContactConfigSchema,
  blockContactDemoData,
  blockDeliveryStepperConfigSchema,
  blockDeliveryStepperDemoData,
  blockDiscountCodesConfigSchema,
  blockDiscountCodesDemoData,
  blockHighlightBoxConfigSchema,
  blockHighlightBoxDemoData,
  blockImagePlaceholderConfigSchema,
  blockImagePlaceholderDemoData,
  blockKpiRowConfigSchema,
  blockKpiRowDemoData,
  blockLateFeesConfigSchema,
  blockLateFeesDemoData,
  blockLineChartConfigSchema,
  blockLineChartDemoData,
  blockLineItemsConfigSchema,
  blockLineItemsDemoData,
  blockLoyaltyBannerConfigSchema,
  blockLoyaltyBannerDemoData,
  blockMultiCurrencyConfigSchema,
  blockMultiCurrencyDemoData,
  blockPaymentHistoryConfigSchema,
  blockPaymentHistoryDemoData,
  blockQrPayConfigSchema,
  blockQrPayDemoData,
  blockRecurringBannerConfigSchema,
  blockRecurringBannerDemoData,
  blockSignatureConfigSchema,
  blockSignatureDemoData,
  blockTaxBreakdownConfigSchema,
  blockTaxBreakdownDemoData,
  blockTermsCheckboxConfigSchema,
  blockTermsCheckboxDemoData,
  blockTotalsSummaryConfigSchema,
  blockTotalsSummaryDemoData,
  blockTwoColTableConfigSchema,
  blockTwoColTableDemoData,
  documentCanvasConfigSchema,
  documentCanvasDemoData,
  type BlockApprovalConfig,
  type BlockAttachmentsConfig,
  type BlockBarChartConfig,
  type BlockContactConfig,
  type BlockDeliveryStepperConfig,
  type BlockDiscountCodesConfig,
  type BlockHighlightBoxConfig,
  type BlockImagePlaceholderConfig,
  type BlockKpiRowConfig,
  type BlockLateFeesConfig,
  type BlockLineChartConfig,
  type BlockLineItemsConfig,
  type BlockLoyaltyBannerConfig,
  type BlockMultiCurrencyConfig,
  type BlockPaymentHistoryConfig,
  type BlockQrPayConfig,
  type BlockRecurringBannerConfig,
  type BlockSignatureConfig,
  type BlockTaxBreakdownConfig,
  type BlockTermsCheckboxConfig,
  type BlockTotalsPayload,
  type BlockTotalsSummaryConfig,
  type BlockTwoColTableConfig,
} from './blocks-config.js';
export { blocksTrackDefinitions } from './blocks-track.definitions.js';
