/**
 * `domain` family public surface (annex §13) — the two M7 exit-criteria widgets
 * (`org-chart`, `gantt-chart`) plus their registry metadata and pure geometry.
 * Component code is also reachable through each definition's `lazy()` ref, so
 * the registry still emits one chunk per family (04 §2.3); this barrel is for
 * direct template/story composition and tests. Registry metadata lives in
 * `domain-track.definitions.ts`.
 *
 * TRACK BUILDER (M7 Wave 4) added the §13 DOCUMENT half below: `document-canvas`
 * and its 22-block shared library. The ops/billing/API cards land beside them.
 */
export {
  OrgChart,
  OrgChartWidget,
  orgChartConfigSchema,
  orgChartDemoData,
  type OrgChartConfig,
  type OrgChartProps,
} from './OrgChart.js';
export {
  GanttChart,
  GanttChartWidget,
  ganttChartConfigSchema,
  ganttChartDemoData,
  ganttRowsOf,
  type GanttChartConfig,
  type GanttChartProps,
} from './GanttChart.js';
export { GANTT_DEMO_TODAY_MS } from './domain-config.js';
export {
  DAY_MS,
  DOMAIN_DEMO_EPOCH,
  buildOrgTree,
  categoryTone,
  countNodes,
  dayOffset,
  dayToPercent,
  daysToPercent,
  groupSpan,
  layoutOrgTree,
  mulberry32,
  orgRootsOf,
  parseDateMs,
  toGanttModel,
  toneOf,
  weekTicks,
  type GanttFieldMap,
  type GanttModelOptions,
  type OrgConnector,
  type OrgFieldMap,
  type OrgLayout,
  type OrgLayoutNode,
  type OrgLayoutOptions,
} from './domain-lib.js';
export type {
  GanttData,
  GanttGroup,
  GanttModel,
  GanttTask,
  OrgNode,
  OrgNodeMeta,
  OrgTreeData,
} from './domain-types.js';
export {
  domainTrackDefinitions,
  ganttChartDefinition,
  orgChartDefinition,
} from './domain-track.definitions.js';

// ── TRACK BUILDER (M7 Wave 4): document-canvas + the 22-block vocabulary ─────

export { DocumentCanvasWidget, type DocumentCanvasConfig } from './DocumentCanvas.js';
export {
  BlockDiscountCodesWidget,
  BlockLateFeesWidget,
  BlockLineItemsWidget,
  BlockMultiCurrencyWidget,
  BlockPaymentHistoryWidget,
  BlockQrPayWidget,
  BlockTaxBreakdownWidget,
  BlockTotalsSummaryWidget,
} from './BlockFinancial.js';
export {
  BlockAttachmentsWidget,
  BlockBarChartWidget,
  BlockImagePlaceholderWidget,
  BlockKpiRowWidget,
  BlockLineChartWidget,
  BlockTwoColTableWidget,
} from './BlockReport.js';
export {
  BlockApprovalWidget,
  BlockDeliveryStepperWidget,
  BlockLoyaltyBannerWidget,
  BlockRecurringBannerWidget,
  BlockSignatureWidget,
  BlockTermsCheckboxWidget,
} from './BlockStatus.js';
export { BlockContactWidget, BlockHighlightBoxWidget } from './BlockContent.js';
export { BlockCallout, BlockEmpty, BlockSection, MoneyRow, fillTemplate } from './BlockShell.js';
export {
  BLOCK_DAY_MS,
  BLOCK_DEMO_EPOCH,
  BLOCK_IDS,
  DOC_TYPES,
  DOC_TYPE_BLOCKS,
  blockBindingSourceOf,
  blockDataOf,
  blockOrderOf,
  categoricalData,
  categoricalItemsOf,
  computeTotals,
  docTypeOf,
  formatBlockDate,
  formatBlockMoney,
  formatBlockNumber,
  formatBlockRate,
  formatBlockSize,
  isBlockId,
  lineItemsOf,
  maskMethod,
  moveBlock,
  rowData,
  rowOf,
  rowsData,
  rowsOf,
  round2,
  twoColRowsOf,
  type BlockBindingSource,
  type BlockId,
} from './block-lib.js';
export type {
  BlockApproval,
  BlockAttachment,
  BlockContact,
  BlockDiscountCode,
  BlockFxLine,
  BlockHighlight,
  BlockImagePlaceholder,
  BlockKpi,
  BlockLateFees,
  BlockLoyalty,
  BlockMultiCurrency,
  BlockPayment,
  BlockQrPay,
  BlockRecurring,
  BlockSignature,
  BlockStep,
  BlockTaxLine,
  BlockTerms,
  BlockTwoColRow,
  CategoricalData,
  DocBlockInstance,
  DocData,
  DocLineItem,
  DocRates,
  DocRecord,
  DocTotals,
  DocType,
  RowData,
  RowsData,
} from './block-types.js';
export {
  blockApprovalConfigSchema,
  blockApprovalDemoData,
  blockAttachmentsConfigSchema,
  blockAttachmentsDemoData,
  blockBarChartConfigSchema,
  blockBarChartDemoData,
  blockContactConfigSchema,
  blockContactDemoData,
  blockDeliveryStepperConfigSchema,
  blockDeliveryStepperDemoData,
  blockDiscountCodesConfigSchema,
  blockDiscountCodesDemoData,
  blockHighlightBoxConfigSchema,
  blockHighlightBoxDemoData,
  blockImagePlaceholderConfigSchema,
  blockImagePlaceholderDemoData,
  blockKpiRowConfigSchema,
  blockKpiRowDemoData,
  blockLateFeesConfigSchema,
  blockLateFeesDemoData,
  blockLineChartConfigSchema,
  blockLineChartDemoData,
  blockLineItemsConfigSchema,
  blockLineItemsDemoData,
  blockLoyaltyBannerConfigSchema,
  blockLoyaltyBannerDemoData,
  blockMultiCurrencyConfigSchema,
  blockMultiCurrencyDemoData,
  blockPaymentHistoryConfigSchema,
  blockPaymentHistoryDemoData,
  blockQrPayConfigSchema,
  blockQrPayDemoData,
  blockRecurringBannerConfigSchema,
  blockRecurringBannerDemoData,
  blockSignatureConfigSchema,
  blockSignatureDemoData,
  blockTaxBreakdownConfigSchema,
  blockTaxBreakdownDemoData,
  blockTermsCheckboxConfigSchema,
  blockTermsCheckboxDemoData,
  blockTotalsSummaryConfigSchema,
  blockTotalsSummaryDemoData,
  blockTwoColTableConfigSchema,
  blockTwoColTableDemoData,
  documentCanvasConfigSchema,
  documentCanvasDemoData,
  type BlockApprovalConfig,
  type BlockAttachmentsConfig,
  type BlockBarChartConfig,
  type BlockContactConfig,
  type BlockDeliveryStepperConfig,
  type BlockDiscountCodesConfig,
  type BlockHighlightBoxConfig,
  type BlockImagePlaceholderConfig,
  type BlockKpiRowConfig,
  type BlockLateFeesConfig,
  type BlockLineChartConfig,
  type BlockLineItemsConfig,
  type BlockLoyaltyBannerConfig,
  type BlockMultiCurrencyConfig,
  type BlockPaymentHistoryConfig,
  type BlockQrPayConfig,
  type BlockRecurringBannerConfig,
  type BlockSignatureConfig,
  type BlockTaxBreakdownConfig,
  type BlockTermsCheckboxConfig,
  type BlockTotalsPayload,
  type BlockTotalsSummaryConfig,
  type BlockTwoColTableConfig,
} from './blocks-config.js';
export { blocksTrackDefinitions } from './blocks-track.definitions.js';

// ── TRACK OPS (M7 Wave 4): the §13 ops / billing / API / marketing tail ──────
// The eighteen ids that close the annex catalog at 176/176.

export { SloMonitorCardView, SloMonitorCardWidget } from './SloMonitorCard.js';
export { UptimeSegmentBarView, UptimeSegmentBarWidget } from './UptimeSegmentBar.js';
export { ExperimentVariantCompareView, ExperimentVariantCompareWidget } from './ExperimentVariantCompare.js';
export { CreditCardTileView, CreditCardTileWidget } from './CreditCardTile.js';
export { PlanPricingCardsView, PlanPricingCardsWidget } from './PlanPricingCards.js';
export { ApiKeysPanelView, ApiKeysPanelWidget } from './ApiKeysPanel.js';
export { ApiPlaygroundView, ApiPlaygroundWidget } from './ApiPlayground.js';
export {
  LiveTimerView,
  LiveTimerWidget,
  SyncStatusCardView,
  SyncStatusCardWidget,
  timerSeconds,
} from './OpsMonitoring.js';
export {
  CodeSnippetBlockView,
  CodeSnippetBlockWidget,
  ResourceApiCardView,
  ResourceApiCardWidget,
  WebhookEndpointsListView,
  WebhookEndpointsListWidget,
} from './OpsApi.js';
export {
  IpAllowlistCardView,
  IpAllowlistCardWidget,
  PolicyListView,
  PolicyListWidget,
  TestimonialCardView,
  TestimonialCardWidget,
  TrustBadgesView,
  TrustBadgesWidget,
  type AllowlistEntry,
} from './OpsTrust.js';
export {
  OnboardingChecklistView,
  OnboardingChecklistWidget,
  StarterTemplatePickerView,
  StarterTemplatePickerWidget,
} from './OpsOnboarding.js';
export { OpsEmpty, type OpsEmptyProps } from './OpsEmpty.js';
export {
  OPS_DEMO_NOW_MS,
  apiKeysPanelConfigSchema,
  apiKeysPanelDemoData,
  apiPlaygroundConfigSchema,
  apiPlaygroundDemoData,
  codeSnippetBlockConfigSchema,
  codeSnippetBlockDemoData,
  creditCardTileConfigSchema,
  creditCardTileDemoData,
  experimentVariantCompareConfigSchema,
  experimentVariantCompareDemoData,
  ipAllowlistCardConfigSchema,
  ipAllowlistCardDemoData,
  liveTimerConfigSchema,
  liveTimerDemoData,
  onboardingChecklistConfigSchema,
  onboardingChecklistDemoData,
  planPricingCardsConfigSchema,
  planPricingCardsDemoData,
  policyListConfigSchema,
  policyListDemoData,
  resourceApiCardConfigSchema,
  resourceApiCardDemoData,
  sloMonitorCardConfigSchema,
  sloMonitorCardDemoData,
  starterTemplatePickerConfigSchema,
  starterTemplatePickerDemoData,
  syncStatusCardConfigSchema,
  syncStatusCardDemoData,
  testimonialCardConfigSchema,
  testimonialCardDemoData,
  trustBadgesConfigSchema,
  trustBadgesDemoData,
  uptimeSegmentBarConfigSchema,
  uptimeSegmentBarDemoData,
  webhookEndpointsListConfigSchema,
  webhookEndpointsListDemoData,
  type ApiKeysPanelConfig,
  type ApiPlaygroundConfig,
  type CodeSnippetBlockConfig,
  type CreditCardTileConfig,
  type ExperimentVariantCompareConfig,
  type IpAllowlistCardConfig,
  type LiveTimerConfig,
  type OnboardingChecklistConfig,
  type PlanPricingCardsConfig,
  type PolicyListConfig,
  type ResourceApiCardConfig,
  type SloMonitorCardConfig,
  type StarterTemplatePickerConfig,
  type SyncStatusCardConfig,
  type TestimonialCardConfig,
  type TrustBadgesConfig,
  type UptimeSegmentBarConfig,
  type WebhookEndpointsListConfig,
} from './domain-ops-config.js';
export {
  CARD_BRANDS,
  HTTP_METHODS,
  UPTIME_STATES,
  type ApiKeyRecord,
  type CardBrand,
  type ExperimentVariant,
  type HttpMethod,
  type OnboardingTask,
  type OpsListData,
  type OpsRecordData,
  type PaymentMethod,
  type PlaygroundEndpoint,
  type PricingPlan,
  type ResourceApi,
  type RlsPolicy,
  type SloMonitor,
  type StarterDef,
  type SyncStatus,
  type Testimonial,
  type TimerState,
  type UptimeDay,
  type UptimeState,
  type WebhookEndpoint,
} from './domain-ops-types.js';
export {
  METHOD_TONE,
  OPS_TONE_BG,
  OPS_TONE_BORDER_S,
  OPS_TONE_TEXT,
  UPTIME_HEIGHT,
  UPTIME_TONE,
  annualMonthly,
  annualTotal,
  booleanField,
  budgetTone,
  cardBrandOf,
  confidenceTone,
  countField,
  formatCompact,
  formatCount,
  formatDay,
  formatDuration,
  formatMinutes,
  formatMoney,
  formatMs,
  formatPct,
  formatSince,
  formatStamp,
  httpMethodOf,
  instantField,
  interpolate,
  labelField,
  liftPct,
  maskPan,
  maskSecret,
  numberArrayField,
  oneOf,
  opsBindingSourceOf,
  opsRowOf,
  opsRowsOf,
  pctField,
  resolveNow,
  stringArrayField,
  uptimePct,
  uptimeStateOf,
  type OpsBindingSource,
} from './domain-ops-lib.js';
export {
  apiKeysPanelDefinition,
  apiPlaygroundDefinition,
  codeSnippetBlockDefinition,
  creditCardTileDefinition,
  domainOpsTrackDefinitions,
  experimentVariantCompareDefinition,
  ipAllowlistCardDefinition,
  liveTimerDefinition,
  onboardingChecklistDefinition,
  planPricingCardsDefinition,
  policyListDefinition,
  resourceApiCardDefinition,
  sloMonitorCardDefinition,
  starterTemplatePickerDefinition,
  syncStatusCardDefinition,
  testimonialCardDefinition,
  trustBadgesDefinition,
  uptimeSegmentBarDefinition,
  webhookEndpointsListDefinition,
} from './domain-ops-track.definitions.js';
