import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  applyClassification,
  generatePages,
  parseDatabaseModel,
  type GenerateIntent,
  type PageEnvelope,
} from '../src/index.js';

/**
 * **The M7 archetype step is additive — this is the guard that says so.**
 *
 * `northwind.pages.baseline.json` was generated by `generatePages()` on the
 * commit BEFORE the §14 archetype pass existed, and holds every `page-crud` and
 * `page-dashboard` envelope it produced for each intent. The v0.1 gate is built
 * on that output, so the archetype work may add pages and may not touch these —
 * not their config, not their nav order, not their slugs, and not their
 * `generatedHash` (H5 keys regeneration-in-place off that hash, so a silent
 * change here would re-write every user's untouched pages on the next sync).
 *
 * If a change to `crud.ts` / `dashboard.ts` is ever *intended*, that is a
 * deliberate act: re-record this fixture in the same commit and say so.
 */

const modelPath = fileURLToPath(new URL('./fixtures/northwind.model.json', import.meta.url));
const model = applyClassification(parseDatabaseModel(readFileSync(modelPath, 'utf8')));
const baselinePath = fileURLToPath(
  new URL('./fixtures/northwind.pages.baseline.json', import.meta.url),
);

interface Baseline {
  pages: PageEnvelope[];
  warnings: string[];
}

const baseline = JSON.parse(readFileSync(baselinePath, 'utf8')) as Record<string, Baseline>;
const CONN = 'conn_01HZX0000000000000000000';

const INTENTS: GenerateIntent[] = ['full-admin', 'read-only-analytics', 'crud'];

describe('the pre-archetype crud/dashboard output is unchanged', () => {
  it.each(INTENTS)('intent %s emits byte-identical page-crud/page-dashboard envelopes', (intent) => {
    const expected = baseline[intent] as Baseline;
    expect(expected.pages.length).toBeGreaterThan(0); // an empty fixture would pass vacuously
    const result = generatePages(model, { connectionId: CONN, intent });
    const legacy = result.pages.filter(
      (page) => page.template === 'page-crud' || page.template === 'page-dashboard',
    );
    // Ordering, ids, nav orders, config bodies and generatedHash — all of it.
    expect(JSON.parse(JSON.stringify(legacy))).toEqual(expected.pages);
  });

  it.each(INTENTS)('intent %s keeps every pre-existing warning', (intent) => {
    const expected = baseline[intent] as Baseline;
    const result = generatePages(model, { connectionId: CONN, intent });
    // Archetype warnings may be *added*; none of the old ones may disappear.
    for (const warning of expected.warnings) {
      expect(result.warnings).toContain(warning);
    }
  });

  it('adds pages rather than replacing them', () => {
    const result = generatePages(model, { connectionId: CONN });
    const expected = baseline['full-admin'] as Baseline;
    expect(result.pages.length).toBeGreaterThanOrEqual(expected.pages.length);
    // Northwind's own §14 triggers: employees.reports_to → page-directory,
    // orders.order_date + a title column → page-calendar.
    const added = result.pages.filter(
      (page) => page.template !== 'page-crud' && page.template !== 'page-dashboard',
    );
    expect(added.map((p) => p.template).sort()).toEqual(['page-calendar', 'page-directory']);
  });

  it('leaves every baseline page id and slug in place', () => {
    const result = generatePages(model, { connectionId: CONN });
    const expected = baseline['full-admin'] as Baseline;
    const ids = new Set(result.pages.map((p) => p.id));
    const slugs = new Set(result.pages.map((p) => p.nav.slug));
    for (const page of expected.pages) {
      expect(ids.has(page.id)).toBe(true);
      expect(slugs.has(page.nav.slug)).toBe(true);
    }
    // …and the additions collide with nothing.
    expect(new Set(result.pages.map((p) => p.id)).size).toBe(result.pages.length);
    expect(new Set(result.pages.map((p) => p.nav.slug)).size).toBe(result.pages.length);
  });
});
