/**
 * make-icons.mjs — derive every platform icon from the one vector master.
 * 11-electron.md §10 ("Icons: … generated by a repeatable script … so accent
 * changes re-derive cleanly. Deliverable, not a manual export"), owned by 11-T13.
 *
 * INPUT   apps/desktop/resources/icons/icon-master.svg   (the only checked-in
 *         icon source; the outputs below are gitignored)
 * OUTPUT  apps/desktop/resources/icons/
 *           icon.icns          → electron-builder mac.icon
 *           icon.ico           → electron-builder win.icon
 *           icon.png (1024)    → electron-builder linux.icon
 *           {16,32,64,128,256,512,1024}x{…}.png   → Linux hicolor set + runtime
 *
 * WHY A SCRIPT, NOT A CHECKED-IN BINARY. The master carries two colours and
 * nothing else (see the SVG); this script re-reads the ACTIVE accent straight
 * from @adminium/tokens and substitutes it before rasterizing, so the day the
 * brand accent changes in packages/tokens the icons re-derive with one command
 * and cannot drift from the design system. `ADMINIUM_ICON_ACCENT=<name>` overrides
 * the accent read (default: indigo, the tokens default).
 *
 * WHY IT RESOLVES ITS DEPS FROM apps/desktop. `sharp` (rasterize/resize) and
 * `icon-gen` (assemble .icns/.ico) are build-only devDependencies of the
 * packaging track, so they live in apps/desktop/node_modules, not the repo root
 * where this file sits. It anchors a require there rather than assuming a hoist.
 * If they are absent it says exactly how to install them and exits non-zero
 * rather than emitting a half-set or a fake — an icon that silently didn't
 * regenerate is the "green but broken" trap this milestone keeps hitting.
 */

import { copyFile, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '..');
const desktopDir = resolve(repoRoot, 'apps', 'desktop');
const tokensDir = resolve(repoRoot, 'packages', 'tokens', 'src');
const iconsDir = resolve(desktopDir, 'resources', 'icons');
const masterSvgPath = resolve(iconsDir, 'icon-master.svg');

// The two colours baked into the master, replaced with the resolved tokens
// values before rasterizing. Must stay in lockstep with icon-master.svg.
const MASTER_ACCENT = '#4f46e5'; // [data-accent="indigo"] --accent
const MASTER_ACCENT_FG = '#ffffff'; // --accent-fg

// PNG raster sizes. The superset covers what .icns wants (16→1024, doubling) and
// what .ico wants (up to 256, plus 24/48). The WxW.png names are the freedesktop
// hicolor convention electron-builder's linux icon collector understands.
//
// This list is a CONTRACT with icon-gen: when a PNG directory is the input,
// icon-gen unions the REQUIRED_IMAGE_SIZES of every enabled output format and
// `statSync`s `<staging>/<size>.png` for each — a missing one throws ENOENT, it
// does not degrade. icns wants [16,32,64,128,256,512,1024]; ico wants
// [16,24,32,48,64,128,256]; their union is exactly this array. (favicon would
// additionally want 57/72/96/120/144/152/195/228, which is why the call below
// must NOT enable it — see the comment there.)
const PNG_SIZES = [16, 24, 32, 48, 64, 128, 256, 512, 1024];
const HICOLOR_SIZES = [16, 32, 64, 128, 256, 512, 1024];

function fail(message) {
  process.stderr.write(`make-icons: ${message}\n`);
  process.exit(1);
}

/** Resolve a build-only dep from apps/desktop, or explain how to install it. */
async function loadDesktopDep(name) {
  const desktopRequire = createRequire(pathToFileURL(join(desktopDir, 'package.json')));
  let resolved;
  try {
    resolved = desktopRequire.resolve(name);
  } catch {
    fail(
      `\`${name}\` is not installed. sharp + icon-gen are build-only ` +
        'devDependencies of @adminium/desktop (the packaging track):\n\n' +
        '  pnpm --filter @adminium/desktop add -D sharp icon-gen\n\n' +
        'then re-run:  pnpm --filter @adminium/desktop icons',
    );
  }
  const mod = await import(pathToFileURL(resolved));
  return mod.default ?? mod;
}

/** Pull a hex colour out of a tokens CSS file, or throw with the file named. */
function extractHex(css, pattern, label, file) {
  const match = css.match(pattern);
  if (!match) fail(`could not read ${label} from ${file} — has the token moved?`);
  return match[1];
}

async function resolveAccent() {
  const accentName = process.env.ADMINIUM_ICON_ACCENT ?? 'indigo';
  const accentsCss = await readFile(resolve(tokensDir, 'accents.css'), 'utf8');
  const tokensCss = await readFile(resolve(tokensDir, 'tokens.css'), 'utf8');
  const accent = extractHex(
    accentsCss,
    new RegExp(`\\[data-accent="${accentName}"\\]\\s*\\{\\s*--accent:\\s*(#[0-9a-fA-F]{3,8})`),
    `accent "${accentName}"`,
    'packages/tokens/src/accents.css',
  );
  const accentFg = extractHex(
    tokensCss,
    /--accent-fg:\s*(#[0-9a-fA-F]{3,8})/,
    '--accent-fg',
    'packages/tokens/src/tokens.css',
  );
  return { accentName, accent, accentFg };
}

async function main() {
  const [sharp, iconGen, { accentName, accent, accentFg }] = await Promise.all([
    loadDesktopDep('sharp'),
    loadDesktopDep('icon-gen'),
    resolveAccent(),
  ]);

  const masterSvg = await readFile(masterSvgPath, 'utf8');
  // Global, case-insensitive: the master holds these two colours and no others.
  const svg = masterSvg
    .replaceAll(new RegExp(MASTER_ACCENT, 'gi'), accent)
    .replaceAll(new RegExp(MASTER_ACCENT_FG, 'gi'), accentFg);
  const svgBuffer = Buffer.from(svg);

  // A temp dir of size-named PNGs is icon-gen's `type: 'png'` input contract; it
  // also lets us skip icon-gen's own SVG rasterizer (heavier, and it would read
  // the un-substituted file on disk instead of our accent-swapped buffer).
  const stagingDir = await mkdtemp(join(tmpdir(), 'adminium-icons-'));
  try {
    await Promise.all(
      PNG_SIZES.map(async (size) => {
        const png = await sharp(svgBuffer, { density: 384 })
          .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
          .png()
          .toBuffer();
        await writeFile(join(stagingDir, `${size}.png`), png);
        // The freedesktop-named copies (and icon.png) ship in resources/icons.
        if (HICOLOR_SIZES.includes(size)) {
          await writeFile(join(iconsDir, `${size}x${size}.png`), png);
        }
        if (size === 1024) await writeFile(join(iconsDir, 'icon.png'), png);
      }),
    );

    // Assemble the container formats from the staged PNGs. We adopt whatever
    // paths icon-gen returns by EXTENSION and copy them to the stable names
    // electron-builder.yml points at (icon.icns / icon.ico), rather than trusting
    // icon-gen's output-naming options — those keys have shifted across major
    // versions, and a wrong key would silently leave the default-named file the
    // yml can't find. Output lands in the staging dir (cleaned in `finally`).
    //
    // THE OPTIONS SHAPE IS VERSION-SENSITIVE — icon-gen v5's ICONOptions is
    // `{ ico?, icns?, favicon?, report }`. The pre-v2 `{ type, modes }` spelling
    // is not merely ignored: unrecognised keys leave all three format flags
    // unset, which trips icon-gen's "output all by default" branch and silently
    // ENABLES favicon, whose required sizes (57/72/96/…/228) this script does not
    // rasterize — so the run dies on `statSync('<staging>/57.png')`. Naming
    // `icns` and `ico` explicitly, and omitting `favicon`, is what pins the
    // required-size set to a subset of PNG_SIZES above. Empty objects mean
    // "default name, all required sizes".
    const produced = await iconGen(stagingDir, stagingDir, {
      icns: {},
      ico: {},
      report: false,
    });
    const icns = produced.find((p) => p.toLowerCase().endsWith('.icns'));
    const ico = produced.find((p) => p.toLowerCase().endsWith('.ico'));
    if (!icns || !ico) {
      fail(`icon-gen did not produce both .icns and .ico (got: ${produced.join(', ') || 'nothing'})`);
    }
    await copyFile(icns, join(iconsDir, 'icon.icns'));
    await copyFile(ico, join(iconsDir, 'icon.ico'));
  } finally {
    await rm(stagingDir, { recursive: true, force: true });
  }

  process.stdout.write(
    `make-icons: derived icon.icns / icon.ico / icon.png + ${HICOLOR_SIZES.length} PNGs ` +
      `into apps/desktop/resources/icons using accent "${accentName}" (${accent}).\n`,
  );
}

main().catch((err) => fail(err?.stack ?? String(err)));
