// SPDX-License-Identifier: AGPL-3.0-only
/**
 * @adminium/manifest — Micro-SaaS manifest spec v1.
 *
 * The frozen envelope schema + validator (browser-safe, pure Zod), and the
 * install planner (`requiredSchema` → create-or-map diff, `plan.ts`) that both
 * install paths run: add-ons since, apps since. The DDL that applies a plan
 * lives server-side in `apps/server/src/add-ons/install-ddl.ts`; nothing in
 * this package does I/O.
 */
export const PACKAGE_NAME = '@adminium/manifest';

export {
  MANIFEST_VERSION,
  MANIFEST_KINDS,
  MANIFEST_CATEGORIES,
  MANIFEST_CAPABILITIES,
  RESERVED_KEYS,
  COLUMN_TYPES,
  COLUMN_SEMANTICS,
  COLUMN_ROLES,
  FRONTEND_KINDS,
  FIRST_PARTY_PUBLISHER_ID,
  LOCAL_PUBLISHER_ID,
  manifestSchema,
  appManifestSchema,
  addOnManifestSchema,
  manifestKindSchema,
  addOnIssues,
  isAddOnManifest,
  identitySchema,
  compatibilitySchema,
  requiredSchemaSchema,
  requiredTableSchema,
  requiredColumnSchema,
  pageSchema,
  roleSchema,
  settingSchema,
  seedSchema,
  frontendSchema,
  capabilitySchema,
  categorySchema,
  publisherSchema,
  i18nMessageSchema,
  compareSemver,
  defaultIssue,
  MAX_TEXT_LENGTH,
  MAX_TABLE_NAME,
  prefixFor,
  appReferenceIssues,
  ADD_ON_INSTALL_FLOOR,
  MAX_SEED_ROWS,
  installsLikeAnApp,
  ledgersOf,
  adjusterOf,
  lookUpOf,
  wordsOf,
  indexSetIssues,
  tableIndexesSchema,
  addOnTableSchema,
  type AddOnTable,
  columnRulesSchema,
  stampSetSchema,
  stampTriggerSchema,
  shapeDefinitionSchema,
  shapePartSchema,
  shapeDefinitionIssues,
  capacitySchema,
  navGroupSchema,
  publicAccessSchema,
  publicKeysSchema,
  sampleDataSchema,
  labelsSchema,
  type ColumnRules,
  type PublicAccess,
  type Manifest,
  type AppManifest,
  type AddOnManifest,
  type ManifestKind,
  type AddOnBlock,
  type Capability,
  type Publisher,
  type I18nMessage,
  type RequiredTable,
  type RequiredColumn,
  type RequiredTableShape,
  type ShapeDefinition,
} from './schema.js';
export { ROLE_ADD_ON_ACTIONS, roleAddOnTableSchema, roleAddOnTablesSchema, roleLimitSchema, roleLimitsSchema, type RoleAddOnTable, type RoleLimit } from './roles.js';
export { lookUpIssues, lookUpKindSchema, lookUpSchema, type LookUp, type LookUpKind, type LookUpTable } from './look-up.js';
export {
  PAGE_FILTER_CONTROLS,
  pageBulkActionSchema,
  keptFromStaff,
  pageBulkSchema,
  pageConfigIssues,
  pageFilterControls,
  pageFiltersSchema,
  pageTabsSchema,
  type PageBulkAction,
  type PageFilterControl,
  type PageFilters,
  type PageTabs,
} from './page-config.js';
export { STATE_ACTIONS_MAX, stateActionIssues, stateActionKind, stateActionSchema, stateActionsSchema, type StateAction, type StateActionsContext } from './state-actions.js';

export {
  validateManifest,
  isManifestOnly,
  parseManifest,
  manifestWarnings,
  type ValidateManifestResult,
  type ValidateManifestOptions,
  type ManifestIssue,
} from './validate.js';

export { BOOKING_WEEKDAYS, bookingSchema, type BookingRule } from './booking.js';

export {
  capacityListSchema,
  capacityRuleSchema,
  capacityViaColumns,
  isLegacyCapacity,
  kindOf as capacityKindOf,
  rulesOf as capacityRulesOf,
  type Capacity,
  type CapacityKind,
  type CapacityRule,
  type NightCapacityRule,
  type ParentCapacityRule,
  type SlotCapacityRule,
} from './capacity.js';

export {
  OUTBOX_WRITTEN,
  REPEAT_KEY_LENGTH,
  WAS_MIN_LENGTH,
  WITH_ATTACHMENT,
  ONLY_WITH,
  ONLY_WITHOUT,
  GROUPED_FORM,
  groupedCode,
  isCodeColumn,
  clockShaped,
  rulesReading,
  OUTBOX_HELD,
  OUTBOX_SKIP_REASONS,
  OUTBOX_STATUSES,
  emailTemplateSchema,
  emailRowsDataSchema,
  outboxProducerSchema,
  outboxSchema,
  type EmailTemplate,
  type EmailRowsData,
  type Outbox,
  type OutboxProducer,
} from './outbox.js';

export { SELF_UNLOCK_MIN_LENGTH } from './public-access.js';
export { CUSTOMER_KEY, claimKind, claimSchema, codeWhereSchema, ownLinksOfPerson, personalColumn, publicKeySchema, shareCodeColumns, type Claim, type PersonOwnLink, type PublicKey } from './public-access.js';
export { resendAddressOf, type ResendAddress, type ResendColumns, type ResendOutbox } from './public-access.js';
export { PLAIN_TEXT_DIGITS_MOST, PLAIN_TEXT_LONGEST, PLAIN_TEXT_MAX, plainTextMax, plainTextRef, type PlainTextColumnRef } from './public-access.js';

export {
  FORMULA_MAX_DEPTH,
  currencyScale,
  evaluateFormula,
  formulaColumns,
  formulaConditionSchema,
  formulaCycle,
  formulaExprSchema,
  formulaOrder,
  holds as formulaHolds,
  momentColumns,
  momentOf,
  dayColumns,
  dayNumberOf,
  isJoinColumn,
  JOIN_COLUMN_TYPES,
  joinText,
  nightlyRates,
  NightlyRuleUnreadable,
  PER_NIGHT_MAX,
  weekdaysOf,
  ratioText,
  rollupValue,
  sameDecimal,
  toRatio,
  type FormulaCondition,
  type FormulaExpr,
  type Night,
  type NightlyAdjustment,
} from './formula.js';

export {
  moveTarget,
  undoMoveIssues,
  stateChildSchema,
  stateConditionSchema,
  stateMoveSchema,
  statesSchema,
  type StateChild,
  type StateCondition,
  type StateMove,
  type States,
  type UndoColumn,
} from './states.js';
export {
  createRequiresSchema,
  lateMoveSchema,
  linkedConditionSchema,
  settingConditionSchema,
  changeEffectSchema,
  isChangeEffect,
  moveEffectSchema,
  stateEffectSchema,
  strictStatesSchema,
  timeConditionSchema,
  timedMoveSchema,
  type CreateRequires,
  type LateMove,
  type LinkedCondition,
  type SettingCondition,
  type ChangeEffect,
  type MoveEffect,
  type StateEffect,
  type TimeCondition,
  type TimedMove,
} from './states.js';

export { addOnsSchema, namedAddOns, requiresAddOn, type AddOnNeeds } from './add-ons.js';

export { appDocumentSchema, pairSourceSchema, slotMappingSchema, type AppDocument, type PairSource, type SlotMapping } from './documents.js';

export {
  mapRules as mapShapeRules,
  mapStates as mapShapeStates,
  shapeConformanceIssues,
  shapeKey,
  type ShapeColumn,
  type ShapeDefinitionView,
  type ShapeIssue,
  type ShapePart,
} from './shapes.js';

export { addOnSettingRefSchema, settingSourceSchema, type SettingSource } from './refs.js';

export { TABLE_SHAPES, shapeTables, tableShapeIssues, tableShapeOf, type TableShapeIssue } from './table-shapes.js';

export {
  MOMENT_LIMITS,
  clockTimeSchema,
  hoursEdgeSchema,
  momentIssues,
  momentOffsetSchema,
  momentSchema,
  plainMomentSchema,
  rowTimeSchema,
  wallTimeSchema,
  type ClockTime,
  type HoursEdge,
  type Moment,
  type MomentAmount,
  type MomentOffset,
  type PlainMoment,
  type RowTime,
  type WallTime,
} from './refs.js';

export { parseSemverRange, satisfiesSemverRange } from './semver.js';

export {
  planInstall,
  type InstallPlan,
  type PlannedTable,
  type PlannedColumn,
  type PlannedReference,
  type PlanProblem,
  type SchemaModelView,
  type ExistingColumnView,
  type TableAction,
} from './plan.js';

export {
  IDENTIFIER_LIMIT,
  MYSQL_UNIQUE_KEY_BYTES,
  ROLE_SLUG_LIMIT,
  uniqueWithOf,
  uniqueSetName,
  indexSetName,
  plainIndexName,
  uniqueSetBytes,
  type PlanContext,
  type TableChoice,
  type ShareChoice,
  type ShareOffer,
  type TableClass,
  type TableOffer,
  type PlanEdit,
  type InstallTablePlan,
  type TableAction as ContextTableAction,
} from './plan-context.js';

export {
  SAMPLE_FORMAT,
  ROW_DIRECTIVES,
  SAMPLE_WEEKDAYS,
  byClockSchema,
  byStaySchema,
  isoDurationMs,
  sampleBundleIssues,
  sampleSectionIssues,
  sampleBundleSchema,
  sampleDirective,
  sampleRowSchema,
  sampleValueSchema,
  type ByClock,
  type ByStay,
  type SampleBundle,
  type SampleIssue,
  type SampleValue,
} from './sample.js';

export {
  MARKETPLACE_FORMAT,
  MARKETPLACE_KEY_PATTERN,
  MARKETPLACE_VERSION_PATTERN,
  addOnItemWireSchema,
  addOnReleaseWireSchema,
  appItemWireSchema,
  appReleaseWireSchema,
  marketplaceShelfSchema,
  parseShelf,
  type AddOnItemWire,
  type AddOnReleaseWire,
  type AppItemWire,
  type AppReleaseWire,
  type ParsedShelf,
} from './marketplace-wire.js';

export {
  composeManifest,
  locateIssue,
  splitManifest,
  MANIFEST_PARTS,
  MANIFEST_PART_FIELDS,
  type ManifestPartFile,
  type ComposeProblem,
  type ComposeResult,
  type PartOrigin,
} from './compose.js';
export { ADD_ON_INSTALL_BLOCKS, INSTALL_FLOOR_WORD_NAMES, installFloorWords, type ManifestWord, type ManifestWordName } from './words.js';
export {
  LEDGERS_MAX,
  LEDGER_ACTIONS_MAX,
  LEDGER_INPUT_TYPES,
  LEDGER_READS_MAX,
  LEDGER_READ_ROWS,
  LEDGER_WRITES_MAX,
  POSTINGS_PER_TABLE,
  POSTING_PHASES,
  RECEIPT_COLUMNS,
  RECEIPT_KEY,
  ledgerActionSchema,
  ledgerReadSchema,
  ledgerSchema,
  ledgersSchema,
  optionalInput,
  postingFitIssues,
  postingIssues,
  postingMappingSchema,
  postingPointSchema,
  postingSchema,
  postingsSchema,
  readFromSchema,
  receiptTableIssues,
  switchedOffSchema,
  WORDS_IDS_MAX,
  wordsIssues,
  wordsListSchema,
  wordsSchema,
  type StockWords,
  LEDGER_ISSUE_CODES,
  ledgerIssues,
  type LedgerIssue,
  type LedgerIssueCode,
  type LedgerScopeTable,
  type Ledger,
  type LedgerAction,
  type LedgerInputType,
  type LedgerRead,
  type LedgerTableShape,
  type Posting,
  type PostingMapping,
  type PostingPhase,
  type PostingPoint,
  type SwitchedOff,
} from './ledgers.js';
export { ledgerIndexIssues, ledgerIndexes, type LedgerIndex } from './ledger-indexes.js';
export {
  ADJUST_PARTS_MAX,
  adjustDecidedColumns,
  adjustIssues,
  adjustPartSchema,
  adjustSchema,
  adjusterIssues,
  adjusterReadSchema,
  adjusterSchema,
  type Adjust,
  type AdjustPart,
  type AdjustTableShape,
  type Adjuster,
} from './adjust.js';
export {
  AUTOMATION_CONDITION_OPS,
  AUTOMATION_NODES_MAX,
  MANIFEST_AUTOMATIONS_MAX,
  RULE_EMAIL_VARS,
  automationIssues,
  manifestActionSchema,
  manifestAutomationSchema,
  manifestAutomationsSchema,
  manifestConditionSchema,
  manifestGraphSchema,
  manifestNodeSchema,
  manifestTriggerSchema,
  templatePlaceholdersOf,
  type AutomationTableShape,
  type AutomationTemplateShape,
  type ManifestAction,
  type ManifestAutomation,
  type ManifestCondition,
  type ManifestNode,
  type ManifestTrigger,
} from './automations.js';
