// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Type-prefixed monotonic ULID generator for every adminium_* primary key.
 *
 * Format: `<prefix>_<26-char Crockford-base32 ULID>` — e.g. `usr_01J8ME7Q2RZX4V9T6W3YB0KD5N`.
 * The longest registered prefix is 4 chars, so every id fits the portable
 * `char(36)` id column (07-meta-store.md §2.1) with room to spare.
 *
 * ULIDs are lexicographically time-sortable (48-bit ms timestamp + 80-bit
 * randomness); within one millisecond the random part is incremented
 * (monotonic mode) so ids generated by one process always sort in creation
 * order (08-server-api.md §1.5 cursor pagination relies on this).
 */

import { randomBytes } from 'node:crypto';

/** Crockford base32 alphabet (no I, L, O, U). */
const ENCODING = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const TIME_LEN = 10;
const RAND_LEN = 16;
const ULID_LEN = TIME_LEN + RAND_LEN;

/**
 * Prefix registry: every id-bearing adminium_* table has exactly one prefix
 * (07-meta-store.md §3). Junction/KV tables (user_roles, user_prefs,
 * notification_prefs, settings, changelog_seen, migrations ledger) have
 * natural/composite keys and no prefix.
 */
export const ID_PREFIXES = {
  usr: 'adminium_users',
  sess: 'adminium_sessions',
  rst: 'adminium_password_resets',
  key: 'adminium_api_keys',
  role: 'adminium_roles',
  perm: 'adminium_role_permissions',
  aud: 'adminium_audit_log',
  job: 'adminium_jobs',
  conn: 'adminium_connections',
  snap: 'adminium_schema_snapshots',
  ovr: 'adminium_schema_overrides',
  page: 'adminium_pages',
  view: 'adminium_views',
  run: 'adminium_llm_runs',
  ntf: 'adminium_notifications',
  auto: 'adminium_automations',
  arun: 'adminium_automation_runs',
  rep: 'adminium_scheduled_reports',
  exp: 'adminium_exports',
  imp: 'adminium_imports',
  file: 'adminium_files',
  tpl: 'adminium_email_templates',
  wh: 'adminium_webhooks',
  whd: 'adminium_webhook_deliveries',
  flag: 'adminium_feature_flags',
  mft: 'adminium_manifests',
  loc: 'adminium_locales',
  trn: 'adminium_translations',
} as const;

export type IdPrefix = keyof typeof ID_PREFIXES;

const PREFIX_SET: ReadonlySet<string> = new Set(Object.keys(ID_PREFIXES));

/** `<prefix>_<26 Crockford chars>` — Crockford charset excludes I, L, O, U. */
const ID_RE = /^([a-z]{2,4})_([0-9ABCDEFGHJKMNPQRSTVWXYZ]{26})$/;

/** Maximum column width every id must fit (07-meta-store.md §2.1). */
export const ID_MAX_LENGTH = 36;

export class InvalidIdError extends Error {
  override name = 'InvalidIdError';
}

function encodeTime(time: number): string {
  if (!Number.isInteger(time) || time < 0 || time > 2 ** 48 - 1) {
    throw new InvalidIdError(`ULID timestamp out of range: ${time}`);
  }
  let out = '';
  let t = time;
  for (let i = 0; i < TIME_LEN; i += 1) {
    out = ENCODING.charAt(t % 32) + out;
    t = Math.floor(t / 32);
  }
  return out;
}

function decodeTime(chars: string): number {
  let t = 0;
  for (const ch of chars) {
    const v = ENCODING.indexOf(ch);
    if (v < 0) throw new InvalidIdError(`invalid ULID character: ${ch}`);
    t = t * 32 + v;
  }
  return t;
}

/** 16 values in [0, 32); a byte mod 32 is unbiased because 256 % 32 === 0. */
function randomWords(): number[] {
  const bytes = randomBytes(RAND_LEN);
  const out = new Array<number>(RAND_LEN);
  for (let i = 0; i < RAND_LEN; i += 1) out[i] = (bytes[i] as number) % 32;
  return out;
}

let lastTime = -1;
let lastRand: number[] = [];

function incrementRand(rand: number[]): void {
  for (let i = RAND_LEN - 1; i >= 0; i -= 1) {
    const v = rand[i] as number;
    if (v < 31) {
      rand[i] = v + 1;
      return;
    }
    rand[i] = 0;
  }
  // 2^80 increments within one millisecond — not reachable in practice.
  throw new InvalidIdError('monotonic ULID overflow within a single millisecond');
}

/**
 * Generate a new type-prefixed monotonic ULID: `newId('usr')` → `usr_01J…`.
 * Ids from the same process are strictly increasing even within one
 * millisecond or across a backwards clock step.
 */
export function newId(prefix: IdPrefix): string {
  if (!PREFIX_SET.has(prefix)) {
    throw new InvalidIdError(`unknown id prefix: ${String(prefix)}`);
  }
  const t = Date.now();
  if (t <= lastTime) {
    // Same millisecond (or clock regression): stay monotonic by incrementing.
    incrementRand(lastRand);
  } else {
    lastTime = t;
    lastRand = randomWords();
  }
  const rand = lastRand.map((v) => ENCODING.charAt(v)).join('');
  return `${prefix}_${encodeTime(lastTime)}${rand}`;
}

export interface ParsedId {
  /** Registered prefix, e.g. `usr`. */
  prefix: IdPrefix;
  /** The table this id belongs to, e.g. `adminium_users`. */
  table: string;
  /** The bare 26-char ULID. */
  ulid: string;
  /** Millisecond timestamp encoded in the ULID. */
  time: number;
}

/** Parse and validate a prefixed id; throws {@link InvalidIdError} on any malformed input. */
export function parseId(id: string): ParsedId {
  const m = ID_RE.exec(id);
  if (!m) throw new InvalidIdError(`malformed id: ${JSON.stringify(id)}`);
  const [, prefix, ulid] = m as unknown as [string, string, string];
  if (!PREFIX_SET.has(prefix)) throw new InvalidIdError(`unknown id prefix: ${prefix}`);
  if (id.length > ID_MAX_LENGTH) throw new InvalidIdError(`id exceeds char(36): ${id}`);
  return {
    prefix: prefix as IdPrefix,
    table: ID_PREFIXES[prefix as IdPrefix],
    ulid,
    time: decodeTime(ulid.slice(0, TIME_LEN)),
  };
}

/** True when `id` is a well-formed prefixed ULID (optionally of a specific prefix). */
export function isId(id: unknown, prefix?: IdPrefix): boolean {
  if (typeof id !== 'string') return false;
  try {
    const parsed = parseId(id);
    return prefix === undefined || parsed.prefix === prefix;
  } catch {
    return false;
  }
}

/** Millisecond timestamp embedded in a prefixed ULID. */
export function idTime(id: string): number {
  return parseId(id).time;
}

/** Internal — deterministic tests only. */
export function _resetIdState(): void {
  lastTime = -1;
  lastRand = [];
}

export { ULID_LEN as _ULID_LENGTH };
