// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Drift guard for the generated a11y-critical key list (23 §3.3).
 *
 * The list is what stops an admin blanking a button's only accessible name
 * through the Translations editor. It is generated by scanning source for
 * `aria-label={t(…)}`-shaped call sites, so it rots in two directions: a key
 * gets renamed and the entry goes stale, or a new a11y call site lands and
 * nobody regenerates. This suite catches the first; `pnpm gen:a11y-keys`
 * catches the second when it is run.
 */
import { describe, expect, it } from 'vitest';

import { A11Y_CRITICAL_KEYS, isA11yCriticalKey } from './a11y-keys.js';
import { sourceKeyCount, sourceMessage } from './keys.js';

describe('a11y-critical keys', () => {
  it('is non-empty and a strict subset of the authored key surface', () => {
    expect(A11Y_CRITICAL_KEYS.size).toBeGreaterThan(100);
    expect(A11Y_CRITICAL_KEYS.size).toBeLessThan(sourceKeyCount());
  });

  it('names only keys that actually exist in the en-US bundles', () => {
    const missing: string[] = [];
    for (const entry of A11Y_CRITICAL_KEYS) {
      const split = entry.indexOf(':');
      const namespace = entry.slice(0, split);
      const key = entry.slice(split + 1);
      if (sourceMessage(namespace, key) === null) missing.push(entry);
    }
    // A stale entry is harmless at runtime but means the generator's view of
    // the tree has drifted from the bundles — regenerate rather than ignore.
    expect(missing, `stale entries — re-run pnpm --filter @adminium/i18n gen:a11y-keys`).toEqual(
      [],
    );
  });

  it('answers the namespace + key form the server checks with', () => {
    const first = [...A11Y_CRITICAL_KEYS][0] as string;
    const split = first.indexOf(':');
    expect(isA11yCriticalKey(first.slice(0, split), first.slice(split + 1))).toBe(true);
    expect(isA11yCriticalKey('common', 'definitely.not.a.real.key')).toBe(false);
  });
});
