// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Drift guard for the generated a11y-critical key list (23 §3.3).
 *
 * The list is what stops an admin blanking a button's only accessible name
 * through the Translations editor. It is generated by scanning source for
 * `aria-label={t(…)}`-shaped call sites, so it rots in two directions: a key
 * gets renamed and the entry goes stale, or a new a11y call site lands and
 * nobody regenerates. This suite catches both.
 *
 * The second direction went unguarded until 2026-09-14, and in that time the
 * committed list fell 174 keys behind its own generator — every install-wizard
 * label from plan 47 among them — and green throughout, because a missing entry
 * fails nothing until an admin blanks it.
 *
 * That check reads dashboard and widget SOURCE, which is not among this
 * package's turbo inputs, so a cache hit here can replay a pass the tree no
 * longer earns. CI runs `pnpm run a11y-keys-check` outside turbo for that
 * reason; this copy is for `pnpm --filter @adminium/i18n test`.
 */
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { A11Y_CRITICAL_KEYS, isA11yCriticalKey } from './a11y-keys.js';
import { sourceKeyCount, sourceMessage } from './keys.js';

const GENERATOR = join(dirname(fileURLToPath(import.meta.url)), '..', 'scripts', 'gen-a11y-keys.mjs');

describe('a11y-critical keys', () => {
  it('lists every key the generator finds in an accessible-name position', () => {
    // `--check` exits non-zero naming each missing and stale key, and the
    // command that fixes them.
    expect(() => execFileSync('node', [GENERATOR, '--check'], { stdio: 'pipe' })).not.toThrow();
  });

  it('is non-empty and a strict subset of the authored key surface', () => {
    expect(A11Y_CRITICAL_KEYS.size).toBeGreaterThan(100);
    expect(A11Y_CRITICAL_KEYS.size).toBeLessThan(sourceKeyCount());
  });

  it('names only keys that actually exist in the en-US bundles', () => {
    const missing: string[] = [];
    for (const entry of A11Y_CRITICAL_KEYS) {
      const split = entry.indexOf(':');
      const namespace = entry.slice(0, split);
      const key = entry.slice(split + 1);
      if (sourceMessage(namespace, key) === null) missing.push(entry);
    }
    // A stale entry is harmless at runtime but means the generator's view of
    // the tree has drifted from the bundles — regenerate rather than ignore.
    expect(missing, `stale entries — re-run pnpm --filter @adminium/i18n gen:a11y-keys`).toEqual(
      [],
    );
  });

  it('answers the namespace + key form the server checks with', () => {
    const first = [...A11Y_CRITICAL_KEYS][0] as string;
    const split = first.indexOf(':');
    expect(isA11yCriticalKey(first.slice(0, split), first.slice(split + 1))).toBe(true);
    expect(isA11yCriticalKey('common', 'definitely.not.a.real.key')).toBe(false);
  });
});
